// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cartItemFieldNames          = builder.RawFieldNames(&CartItem{})
	cartItemRows                = strings.Join(cartItemFieldNames, ",")
	cartItemRowsExpectAutoSet   = strings.Join(stringx.Remove(cartItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cartItemRowsWithPlaceHolder = strings.Join(stringx.Remove(cartItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCartItemIdPrefix              = "cache:cartItem:id:"
	cacheCartItemUserIdProductIdPrefix = "cache:cartItem:userId:productId:"
)

type (
	cartItemModel interface {
		Insert(ctx context.Context, data *CartItem) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CartItem, error)
		FindOneByUserIdProductId(ctx context.Context, userId uint64, productId uint64) (*CartItem, error)
		Update(ctx context.Context, data *CartItem) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCartItemModel struct {
		sqlc.CachedConn
		table string
	}

	CartItem struct {
		Id         uint64    `db:"id"`
		UserId     uint64    `db:"user_id"`
		ProductId  uint64    `db:"product_id"`
		Quantity   int64     `db:"quantity"`
		Selected   int64     `db:"selected"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newCartItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCartItemModel {
	return &defaultCartItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`cart_item`",
	}
}

func (m *defaultCartItemModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	cartItemIdKey := fmt.Sprintf("%s%v", cacheCartItemIdPrefix, id)
	cartItemUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheCartItemUserIdProductIdPrefix, data.UserId, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, cartItemIdKey, cartItemUserIdProductIdKey)
	return err
}

func (m *defaultCartItemModel) FindOne(ctx context.Context, id uint64) (*CartItem, error) {
	cartItemIdKey := fmt.Sprintf("%s%v", cacheCartItemIdPrefix, id)
	var resp CartItem
	err := m.QueryRowCtx(ctx, &resp, cartItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartItemModel) FindOneByUserIdProductId(ctx context.Context, userId uint64, productId uint64) (*CartItem, error) {
	cartItemUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheCartItemUserIdProductIdPrefix, userId, productId)
	var resp CartItem
	err := m.QueryRowIndexCtx(ctx, &resp, cartItemUserIdProductIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `product_id` = ? limit 1", cartItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, productId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartItemModel) Insert(ctx context.Context, data *CartItem) (sql.Result, error) {
	cartItemIdKey := fmt.Sprintf("%s%v", cacheCartItemIdPrefix, data.Id)
	cartItemUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheCartItemUserIdProductIdPrefix, data.UserId, data.ProductId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, cartItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ProductId, data.Quantity, data.Selected)
	}, cartItemIdKey, cartItemUserIdProductIdKey)
	return ret, err
}

func (m *defaultCartItemModel) Update(ctx context.Context, newData *CartItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	cartItemIdKey := fmt.Sprintf("%s%v", cacheCartItemIdPrefix, data.Id)
	cartItemUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheCartItemUserIdProductIdPrefix, data.UserId, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cartItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ProductId, newData.Quantity, newData.Selected, newData.Id)
	}, cartItemIdKey, cartItemUserIdProductIdKey)
	return err
}

func (m *defaultCartItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCartItemIdPrefix, primary)
}

func (m *defaultCartItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCartItemModel) tableName() string {
	return m.table
}
