// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package server

import (
	"context"

	"mall-product-rpc/internal/logic"
	"mall-product-rpc/internal/svc"
	"mall-product-rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) CreateProduct(ctx context.Context, in *product.CreateProductReq) (*product.CreateProductResp, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductServer) GetProduct(ctx context.Context, in *product.GetProductReq) (*product.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductServer) ListProducts(ctx context.Context, in *product.ListProductsReq) (*product.ListProductsResp, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

func (s *ProductServer) ListShopProducts(ctx context.Context, in *product.ListShopProductsReq) (*product.ListProductsResp, error) {
	l := logic.NewListShopProductsLogic(ctx, s.svcCtx)
	return l.ListShopProducts(in)
}

func (s *ProductServer) UpdateStock(ctx context.Context, in *product.UpdateStockReq) (*product.UpdateStockResp, error) {
	l := logic.NewUpdateStockLogic(ctx, s.svcCtx)
	return l.UpdateStock(in)
}

func (s *ProductServer) SearchProducts(ctx context.Context, in *product.SearchProductsReq) (*product.SearchProductsResp, error) {
	l := logic.NewSearchProductsLogic(ctx, s.svcCtx)
	return l.SearchProducts(in)
}

func (s *ProductServer) LockSku(ctx context.Context, in *product.LockSkuReq) (*product.LockSkuResp, error) {
	l := logic.NewLockSkuLogic(ctx, s.svcCtx)
	return l.LockSku(in)
}

func (s *ProductServer) UnlockSku(ctx context.Context, in *product.UnlockSkuReq) (*product.UnlockSkuResp, error) {
	l := logic.NewUnlockSkuLogic(ctx, s.svcCtx)
	return l.UnlockSku(in)
}

func (s *ProductServer) UpdateProduct(ctx context.Context, in *product.UpdateProductReq) (*product.OkResp, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

func (s *ProductServer) SetProductStatus(ctx context.Context, in *product.SetProductStatusReq) (*product.OkResp, error) {
	l := logic.NewSetProductStatusLogic(ctx, s.svcCtx)
	return l.SetProductStatus(in)
}

func (s *ProductServer) SetProductStock(ctx context.Context, in *product.SetProductStockReq) (*product.OkResp, error) {
	l := logic.NewSetProductStockLogic(ctx, s.svcCtx)
	return l.SetProductStock(in)
}

func (s *ProductServer) MerchantListProducts(ctx context.Context, in *product.MerchantListProductsReq) (*product.ListProductsResp, error) {
	l := logic.NewMerchantListProductsLogic(ctx, s.svcCtx)
	return l.MerchantListProducts(in)
}

func (s *ProductServer) AdminListReviewProducts(ctx context.Context, in *product.AdminListReviewProductsReq) (*product.ListProductsResp, error) {
	l := logic.NewAdminListReviewProductsLogic(ctx, s.svcCtx)
	return l.AdminListReviewProducts(in)
}

func (s *ProductServer) AdminReviewProduct(ctx context.Context, in *product.AdminReviewProductReq) (*product.OkResp, error) {
	l := logic.NewAdminReviewProductLogic(ctx, s.svcCtx)
	return l.AdminReviewProduct(in)
}

func (s *ProductServer) GetProductDetail(ctx context.Context, in *product.GetProductReq) (*product.ProductDetailResp, error) {
	l := logic.NewGetProductDetailLogic(ctx, s.svcCtx)
	return l.GetProductDetail(in)
}
