// Code generated by hand based on goctl template. Safe to edit.
// Source: promotion.proto

package promotionclient

import (
	"context"

	"mall-promotion-rpc/promotion"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty  = promotion.Empty
	OkResp = promotion.OkResp

	Activity                = promotion.Activity
	ActivityTarget          = promotion.ActivityTarget
	ActivityAction          = promotion.ActivityAction
	CreateActivityReq       = promotion.CreateActivityReq
	CreateActivityResp      = promotion.CreateActivityResp
	GetActivityReq          = promotion.GetActivityReq
	GetActivityResp         = promotion.GetActivityResp
	UpdateActivityReq       = promotion.UpdateActivityReq
	ChangeActivityStatusReq = promotion.ChangeActivityStatusReq
	ListActivitiesReq       = promotion.ListActivitiesReq
	ListActivitiesResp      = promotion.ListActivitiesResp

	CouponTemplate                = promotion.CouponTemplate
	CreateCouponTemplateReq       = promotion.CreateCouponTemplateReq
	CreateCouponTemplateResp      = promotion.CreateCouponTemplateResp
	ListCouponTemplatesReq        = promotion.ListCouponTemplatesReq
	ListCouponTemplatesResp       = promotion.ListCouponTemplatesResp
	ChangeCouponTemplateStatusReq = promotion.ChangeCouponTemplateStatusReq

	Coupon            = promotion.Coupon
	ReceiveCouponReq  = promotion.ReceiveCouponReq
	ReceiveCouponResp = promotion.ReceiveCouponResp
	ListMyCouponsReq  = promotion.ListMyCouponsReq
	ListMyCouponsResp = promotion.ListMyCouponsResp

	CartItem      = promotion.CartItem
	PriceConflict = promotion.PriceConflict
	CalcPriceReq  = promotion.CalcPriceReq
	CalcPriceResp = promotion.CalcPriceResp

	LockCouponReq    = promotion.LockCouponReq
	ReleaseCouponReq = promotion.ReleaseCouponReq
	ConsumeCouponReq = promotion.ConsumeCouponReq

	RefundItem     = promotion.RefundItem
	CalcRefundReq  = promotion.CalcRefundReq
	CalcRefundResp = promotion.CalcRefundResp

	Promotion interface {
		CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error)
		GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error)
		UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*OkResp, error)
		ChangeActivityStatus(ctx context.Context, in *ChangeActivityStatusReq, opts ...grpc.CallOption) (*OkResp, error)
		ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error)

		CreateCouponTemplate(ctx context.Context, in *CreateCouponTemplateReq, opts ...grpc.CallOption) (*CreateCouponTemplateResp, error)
		ListCouponTemplates(ctx context.Context, in *ListCouponTemplatesReq, opts ...grpc.CallOption) (*ListCouponTemplatesResp, error)
		ChangeCouponTemplateStatus(ctx context.Context, in *ChangeCouponTemplateStatusReq, opts ...grpc.CallOption) (*OkResp, error)

		ReceiveCoupon(ctx context.Context, in *ReceiveCouponReq, opts ...grpc.CallOption) (*ReceiveCouponResp, error)
		ListMyCoupons(ctx context.Context, in *ListMyCouponsReq, opts ...grpc.CallOption) (*ListMyCouponsResp, error)

		CalcPrice(ctx context.Context, in *CalcPriceReq, opts ...grpc.CallOption) (*CalcPriceResp, error)

		LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*OkResp, error)
		ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*OkResp, error)
		ConsumeCoupon(ctx context.Context, in *ConsumeCouponReq, opts ...grpc.CallOption) (*OkResp, error)

		CalcRefund(ctx context.Context, in *CalcRefundReq, opts ...grpc.CallOption) (*CalcRefundResp, error)
	}

	defaultPromotion struct {
		cli zrpc.Client
	}
)

func NewPromotion(cli zrpc.Client) Promotion {
	return &defaultPromotion{cli: cli}
}

func (m *defaultPromotion) CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).CreateActivity(ctx, in, opts...)
}
func (m *defaultPromotion) GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).GetActivity(ctx, in, opts...)
}
func (m *defaultPromotion) UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*OkResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).UpdateActivity(ctx, in, opts...)
}
func (m *defaultPromotion) ChangeActivityStatus(ctx context.Context, in *ChangeActivityStatusReq, opts ...grpc.CallOption) (*OkResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ChangeActivityStatus(ctx, in, opts...)
}
func (m *defaultPromotion) ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ListActivities(ctx, in, opts...)
}

func (m *defaultPromotion) CreateCouponTemplate(ctx context.Context, in *CreateCouponTemplateReq, opts ...grpc.CallOption) (*CreateCouponTemplateResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).CreateCouponTemplate(ctx, in, opts...)
}
func (m *defaultPromotion) ListCouponTemplates(ctx context.Context, in *ListCouponTemplatesReq, opts ...grpc.CallOption) (*ListCouponTemplatesResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ListCouponTemplates(ctx, in, opts...)
}
func (m *defaultPromotion) ChangeCouponTemplateStatus(ctx context.Context, in *ChangeCouponTemplateStatusReq, opts ...grpc.CallOption) (*OkResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ChangeCouponTemplateStatus(ctx, in, opts...)
}

func (m *defaultPromotion) ReceiveCoupon(ctx context.Context, in *ReceiveCouponReq, opts ...grpc.CallOption) (*ReceiveCouponResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ReceiveCoupon(ctx, in, opts...)
}
func (m *defaultPromotion) ListMyCoupons(ctx context.Context, in *ListMyCouponsReq, opts ...grpc.CallOption) (*ListMyCouponsResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ListMyCoupons(ctx, in, opts...)
}

func (m *defaultPromotion) CalcPrice(ctx context.Context, in *CalcPriceReq, opts ...grpc.CallOption) (*CalcPriceResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).CalcPrice(ctx, in, opts...)
}

func (m *defaultPromotion) LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*OkResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).LockCoupon(ctx, in, opts...)
}
func (m *defaultPromotion) ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*OkResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ReleaseCoupon(ctx, in, opts...)
}
func (m *defaultPromotion) ConsumeCoupon(ctx context.Context, in *ConsumeCouponReq, opts ...grpc.CallOption) (*OkResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).ConsumeCoupon(ctx, in, opts...)
}

func (m *defaultPromotion) CalcRefund(ctx context.Context, in *CalcRefundReq, opts ...grpc.CallOption) (*CalcRefundResp, error) {
	return promotion.NewPromotionClient(m.cli.Conn()).CalcRefund(ctx, in, opts...)
}
