// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: activity/activity.proto

package activity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Activity_CreateActivity_FullMethodName            = "/activity.Activity/CreateActivity"
	Activity_UpdateActivity_FullMethodName            = "/activity.Activity/UpdateActivity"
	Activity_PublishActivity_FullMethodName           = "/activity.Activity/PublishActivity"
	Activity_PauseActivity_FullMethodName             = "/activity.Activity/PauseActivity"
	Activity_EndActivity_FullMethodName               = "/activity.Activity/EndActivity"
	Activity_GetActivity_FullMethodName               = "/activity.Activity/GetActivity"
	Activity_ListActivities_FullMethodName            = "/activity.Activity/ListActivities"
	Activity_Participate_FullMethodName               = "/activity.Activity/Participate"
	Activity_GetParticipation_FullMethodName          = "/activity.Activity/GetParticipation"
	Activity_ListMyParticipations_FullMethodName      = "/activity.Activity/ListMyParticipations"
	Activity_GetActivityStat_FullMethodName           = "/activity.Activity/GetActivityStat"
	Activity_ListTemplates_FullMethodName             = "/activity.Activity/ListTemplates"
	Activity_RegisterTemplate_FullMethodName          = "/activity.Activity/RegisterTemplate"
	Activity_DecrInventory_FullMethodName             = "/activity.Activity/DecrInventory"
	Activity_RestoreInventory_FullMethodName          = "/activity.Activity/RestoreInventory"
	Activity_MarkParticipationRewarded_FullMethodName = "/activity.Activity/MarkParticipationRewarded"
	Activity_MarkParticipationRefunded_FullMethodName = "/activity.Activity/MarkParticipationRefunded"
	Activity_CreateShopCoupon_FullMethodName          = "/activity.Activity/CreateShopCoupon"
	Activity_ListShopCoupons_FullMethodName           = "/activity.Activity/ListShopCoupons"
	Activity_UpdateShopCouponStatus_FullMethodName    = "/activity.Activity/UpdateShopCouponStatus"
	Activity_CreateFlashDiscount_FullMethodName       = "/activity.Activity/CreateFlashDiscount"
	Activity_ListFlashDiscounts_FullMethodName        = "/activity.Activity/ListFlashDiscounts"
	Activity_CancelFlashDiscount_FullMethodName       = "/activity.Activity/CancelFlashDiscount"
)

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityClient interface {
	CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error)
	UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*Empty, error)
	PublishActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	PauseActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	EndActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	GetActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ActivityDetail, error)
	ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error)
	Participate(ctx context.Context, in *ParticipateReq, opts ...grpc.CallOption) (*ParticipateResp, error)
	GetParticipation(ctx context.Context, in *GetParticipationReq, opts ...grpc.CallOption) (*ParticipationRecord, error)
	ListMyParticipations(ctx context.Context, in *ListMyParticipationsReq, opts ...grpc.CallOption) (*ListMyParticipationsResp, error)
	GetActivityStat(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ActivityStat, error)
	ListTemplates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTemplatesResp, error)
	RegisterTemplate(ctx context.Context, in *RegisterTemplateReq, opts ...grpc.CallOption) (*Empty, error)
	DecrInventory(ctx context.Context, in *DecrInventoryReq, opts ...grpc.CallOption) (*DecrInventoryResp, error)
	RestoreInventory(ctx context.Context, in *RestoreInventoryReq, opts ...grpc.CallOption) (*Empty, error)
	MarkParticipationRewarded(ctx context.Context, in *MarkParticipationRewardedReq, opts ...grpc.CallOption) (*Empty, error)
	MarkParticipationRefunded(ctx context.Context, in *MarkParticipationRefundedReq, opts ...grpc.CallOption) (*Empty, error)
	// ===== G-3 Shop coupons =====
	CreateShopCoupon(ctx context.Context, in *CreateShopCouponReq, opts ...grpc.CallOption) (*CreateShopCouponResp, error)
	ListShopCoupons(ctx context.Context, in *ListShopCouponsReq, opts ...grpc.CallOption) (*ListShopCouponsResp, error)
	UpdateShopCouponStatus(ctx context.Context, in *UpdateShopCouponStatusReq, opts ...grpc.CallOption) (*Empty, error)
	// ===== G-4 SKU flash discount =====
	CreateFlashDiscount(ctx context.Context, in *CreateFlashDiscountReq, opts ...grpc.CallOption) (*CreateFlashDiscountResp, error)
	ListFlashDiscounts(ctx context.Context, in *ListFlashDiscountsReq, opts ...grpc.CallOption) (*ListFlashDiscountsResp, error)
	CancelFlashDiscount(ctx context.Context, in *CancelFlashDiscountReq, opts ...grpc.CallOption) (*Empty, error)
}

type activityClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityClient(cc grpc.ClientConnInterface) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateActivityResp)
	err := c.cc.Invoke(ctx, Activity_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_UpdateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) PublishActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_PublishActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) PauseActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_PauseActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) EndActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_EndActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetActivity(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ActivityDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityDetail)
	err := c.cc.Invoke(ctx, Activity_GetActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesResp)
	err := c.cc.Invoke(ctx, Activity_ListActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) Participate(ctx context.Context, in *ParticipateReq, opts ...grpc.CallOption) (*ParticipateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipateResp)
	err := c.cc.Invoke(ctx, Activity_Participate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetParticipation(ctx context.Context, in *GetParticipationReq, opts ...grpc.CallOption) (*ParticipationRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipationRecord)
	err := c.cc.Invoke(ctx, Activity_GetParticipation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) ListMyParticipations(ctx context.Context, in *ListMyParticipationsReq, opts ...grpc.CallOption) (*ListMyParticipationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyParticipationsResp)
	err := c.cc.Invoke(ctx, Activity_ListMyParticipations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetActivityStat(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ActivityStat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityStat)
	err := c.cc.Invoke(ctx, Activity_GetActivityStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) ListTemplates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTemplatesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResp)
	err := c.cc.Invoke(ctx, Activity_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) RegisterTemplate(ctx context.Context, in *RegisterTemplateReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_RegisterTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) DecrInventory(ctx context.Context, in *DecrInventoryReq, opts ...grpc.CallOption) (*DecrInventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrInventoryResp)
	err := c.cc.Invoke(ctx, Activity_DecrInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) RestoreInventory(ctx context.Context, in *RestoreInventoryReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_RestoreInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) MarkParticipationRewarded(ctx context.Context, in *MarkParticipationRewardedReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_MarkParticipationRewarded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) MarkParticipationRefunded(ctx context.Context, in *MarkParticipationRefundedReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_MarkParticipationRefunded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) CreateShopCoupon(ctx context.Context, in *CreateShopCouponReq, opts ...grpc.CallOption) (*CreateShopCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShopCouponResp)
	err := c.cc.Invoke(ctx, Activity_CreateShopCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) ListShopCoupons(ctx context.Context, in *ListShopCouponsReq, opts ...grpc.CallOption) (*ListShopCouponsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopCouponsResp)
	err := c.cc.Invoke(ctx, Activity_ListShopCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) UpdateShopCouponStatus(ctx context.Context, in *UpdateShopCouponStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_UpdateShopCouponStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) CreateFlashDiscount(ctx context.Context, in *CreateFlashDiscountReq, opts ...grpc.CallOption) (*CreateFlashDiscountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFlashDiscountResp)
	err := c.cc.Invoke(ctx, Activity_CreateFlashDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) ListFlashDiscounts(ctx context.Context, in *ListFlashDiscountsReq, opts ...grpc.CallOption) (*ListFlashDiscountsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFlashDiscountsResp)
	err := c.cc.Invoke(ctx, Activity_ListFlashDiscounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) CancelFlashDiscount(ctx context.Context, in *CancelFlashDiscountReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Activity_CancelFlashDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
// All implementations must embed UnimplementedActivityServer
// for forward compatibility.
type ActivityServer interface {
	CreateActivity(context.Context, *CreateActivityReq) (*CreateActivityResp, error)
	UpdateActivity(context.Context, *UpdateActivityReq) (*Empty, error)
	PublishActivity(context.Context, *IdReq) (*Empty, error)
	PauseActivity(context.Context, *IdReq) (*Empty, error)
	EndActivity(context.Context, *IdReq) (*Empty, error)
	GetActivity(context.Context, *IdReq) (*ActivityDetail, error)
	ListActivities(context.Context, *ListActivitiesReq) (*ListActivitiesResp, error)
	Participate(context.Context, *ParticipateReq) (*ParticipateResp, error)
	GetParticipation(context.Context, *GetParticipationReq) (*ParticipationRecord, error)
	ListMyParticipations(context.Context, *ListMyParticipationsReq) (*ListMyParticipationsResp, error)
	GetActivityStat(context.Context, *IdReq) (*ActivityStat, error)
	ListTemplates(context.Context, *Empty) (*ListTemplatesResp, error)
	RegisterTemplate(context.Context, *RegisterTemplateReq) (*Empty, error)
	DecrInventory(context.Context, *DecrInventoryReq) (*DecrInventoryResp, error)
	RestoreInventory(context.Context, *RestoreInventoryReq) (*Empty, error)
	MarkParticipationRewarded(context.Context, *MarkParticipationRewardedReq) (*Empty, error)
	MarkParticipationRefunded(context.Context, *MarkParticipationRefundedReq) (*Empty, error)
	// ===== G-3 Shop coupons =====
	CreateShopCoupon(context.Context, *CreateShopCouponReq) (*CreateShopCouponResp, error)
	ListShopCoupons(context.Context, *ListShopCouponsReq) (*ListShopCouponsResp, error)
	UpdateShopCouponStatus(context.Context, *UpdateShopCouponStatusReq) (*Empty, error)
	// ===== G-4 SKU flash discount =====
	CreateFlashDiscount(context.Context, *CreateFlashDiscountReq) (*CreateFlashDiscountResp, error)
	ListFlashDiscounts(context.Context, *ListFlashDiscountsReq) (*ListFlashDiscountsResp, error)
	CancelFlashDiscount(context.Context, *CancelFlashDiscountReq) (*Empty, error)
	mustEmbedUnimplementedActivityServer()
}

// UnimplementedActivityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityServer struct{}

func (UnimplementedActivityServer) CreateActivity(context.Context, *CreateActivityReq) (*CreateActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedActivityServer) UpdateActivity(context.Context, *UpdateActivityReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (UnimplementedActivityServer) PublishActivity(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishActivity not implemented")
}
func (UnimplementedActivityServer) PauseActivity(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseActivity not implemented")
}
func (UnimplementedActivityServer) EndActivity(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EndActivity not implemented")
}
func (UnimplementedActivityServer) GetActivity(context.Context, *IdReq) (*ActivityDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedActivityServer) ListActivities(context.Context, *ListActivitiesReq) (*ListActivitiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedActivityServer) Participate(context.Context, *ParticipateReq) (*ParticipateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Participate not implemented")
}
func (UnimplementedActivityServer) GetParticipation(context.Context, *GetParticipationReq) (*ParticipationRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipation not implemented")
}
func (UnimplementedActivityServer) ListMyParticipations(context.Context, *ListMyParticipationsReq) (*ListMyParticipationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyParticipations not implemented")
}
func (UnimplementedActivityServer) GetActivityStat(context.Context, *IdReq) (*ActivityStat, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityStat not implemented")
}
func (UnimplementedActivityServer) ListTemplates(context.Context, *Empty) (*ListTemplatesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedActivityServer) RegisterTemplate(context.Context, *RegisterTemplateReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTemplate not implemented")
}
func (UnimplementedActivityServer) DecrInventory(context.Context, *DecrInventoryReq) (*DecrInventoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrInventory not implemented")
}
func (UnimplementedActivityServer) RestoreInventory(context.Context, *RestoreInventoryReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreInventory not implemented")
}
func (UnimplementedActivityServer) MarkParticipationRewarded(context.Context, *MarkParticipationRewardedReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkParticipationRewarded not implemented")
}
func (UnimplementedActivityServer) MarkParticipationRefunded(context.Context, *MarkParticipationRefundedReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkParticipationRefunded not implemented")
}
func (UnimplementedActivityServer) CreateShopCoupon(context.Context, *CreateShopCouponReq) (*CreateShopCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShopCoupon not implemented")
}
func (UnimplementedActivityServer) ListShopCoupons(context.Context, *ListShopCouponsReq) (*ListShopCouponsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopCoupons not implemented")
}
func (UnimplementedActivityServer) UpdateShopCouponStatus(context.Context, *UpdateShopCouponStatusReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShopCouponStatus not implemented")
}
func (UnimplementedActivityServer) CreateFlashDiscount(context.Context, *CreateFlashDiscountReq) (*CreateFlashDiscountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFlashDiscount not implemented")
}
func (UnimplementedActivityServer) ListFlashDiscounts(context.Context, *ListFlashDiscountsReq) (*ListFlashDiscountsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFlashDiscounts not implemented")
}
func (UnimplementedActivityServer) CancelFlashDiscount(context.Context, *CancelFlashDiscountReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelFlashDiscount not implemented")
}
func (UnimplementedActivityServer) mustEmbedUnimplementedActivityServer() {}
func (UnimplementedActivityServer) testEmbeddedByValue()                  {}

// UnsafeActivityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServer will
// result in compilation errors.
type UnsafeActivityServer interface {
	mustEmbedUnimplementedActivityServer()
}

func RegisterActivityServer(s grpc.ServiceRegistrar, srv ActivityServer) {
	// If the following call panics, it indicates UnimplementedActivityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Activity_ServiceDesc, srv)
}

func _Activity_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CreateActivity(ctx, req.(*CreateActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_UpdateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).UpdateActivity(ctx, req.(*UpdateActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_PublishActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).PublishActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_PublishActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).PublishActivity(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_PauseActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).PauseActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_PauseActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).PauseActivity(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_EndActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).EndActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_EndActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).EndActivity(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetActivity(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).ListActivities(ctx, req.(*ListActivitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_Participate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).Participate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_Participate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).Participate(ctx, req.(*ParticipateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetParticipation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetParticipation(ctx, req.(*GetParticipationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_ListMyParticipations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyParticipationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).ListMyParticipations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_ListMyParticipations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).ListMyParticipations(ctx, req.(*ListMyParticipationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetActivityStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetActivityStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetActivityStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetActivityStat(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).ListTemplates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_RegisterTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).RegisterTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_RegisterTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).RegisterTemplate(ctx, req.(*RegisterTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_DecrInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).DecrInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_DecrInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).DecrInventory(ctx, req.(*DecrInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_RestoreInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).RestoreInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_RestoreInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).RestoreInventory(ctx, req.(*RestoreInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_MarkParticipationRewarded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkParticipationRewardedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).MarkParticipationRewarded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_MarkParticipationRewarded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).MarkParticipationRewarded(ctx, req.(*MarkParticipationRewardedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_MarkParticipationRefunded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkParticipationRefundedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).MarkParticipationRefunded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_MarkParticipationRefunded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).MarkParticipationRefunded(ctx, req.(*MarkParticipationRefundedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_CreateShopCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CreateShopCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_CreateShopCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CreateShopCoupon(ctx, req.(*CreateShopCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_ListShopCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopCouponsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).ListShopCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_ListShopCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).ListShopCoupons(ctx, req.(*ListShopCouponsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_UpdateShopCouponStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopCouponStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).UpdateShopCouponStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_UpdateShopCouponStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).UpdateShopCouponStatus(ctx, req.(*UpdateShopCouponStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_CreateFlashDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlashDiscountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CreateFlashDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_CreateFlashDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CreateFlashDiscount(ctx, req.(*CreateFlashDiscountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_ListFlashDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlashDiscountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).ListFlashDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_ListFlashDiscounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).ListFlashDiscounts(ctx, req.(*ListFlashDiscountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_CancelFlashDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelFlashDiscountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).CancelFlashDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_CancelFlashDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).CancelFlashDiscount(ctx, req.(*CancelFlashDiscountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Activity_ServiceDesc is the grpc.ServiceDesc for Activity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActivity",
			Handler:    _Activity_CreateActivity_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _Activity_UpdateActivity_Handler,
		},
		{
			MethodName: "PublishActivity",
			Handler:    _Activity_PublishActivity_Handler,
		},
		{
			MethodName: "PauseActivity",
			Handler:    _Activity_PauseActivity_Handler,
		},
		{
			MethodName: "EndActivity",
			Handler:    _Activity_EndActivity_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _Activity_GetActivity_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _Activity_ListActivities_Handler,
		},
		{
			MethodName: "Participate",
			Handler:    _Activity_Participate_Handler,
		},
		{
			MethodName: "GetParticipation",
			Handler:    _Activity_GetParticipation_Handler,
		},
		{
			MethodName: "ListMyParticipations",
			Handler:    _Activity_ListMyParticipations_Handler,
		},
		{
			MethodName: "GetActivityStat",
			Handler:    _Activity_GetActivityStat_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _Activity_ListTemplates_Handler,
		},
		{
			MethodName: "RegisterTemplate",
			Handler:    _Activity_RegisterTemplate_Handler,
		},
		{
			MethodName: "DecrInventory",
			Handler:    _Activity_DecrInventory_Handler,
		},
		{
			MethodName: "RestoreInventory",
			Handler:    _Activity_RestoreInventory_Handler,
		},
		{
			MethodName: "MarkParticipationRewarded",
			Handler:    _Activity_MarkParticipationRewarded_Handler,
		},
		{
			MethodName: "MarkParticipationRefunded",
			Handler:    _Activity_MarkParticipationRefunded_Handler,
		},
		{
			MethodName: "CreateShopCoupon",
			Handler:    _Activity_CreateShopCoupon_Handler,
		},
		{
			MethodName: "ListShopCoupons",
			Handler:    _Activity_ListShopCoupons_Handler,
		},
		{
			MethodName: "UpdateShopCouponStatus",
			Handler:    _Activity_UpdateShopCouponStatus_Handler,
		},
		{
			MethodName: "CreateFlashDiscount",
			Handler:    _Activity_CreateFlashDiscount_Handler,
		},
		{
			MethodName: "ListFlashDiscounts",
			Handler:    _Activity_ListFlashDiscounts_Handler,
		},
		{
			MethodName: "CancelFlashDiscount",
			Handler:    _Activity_CancelFlashDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity/activity.proto",
}
