// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: review.proto

package reviewclient

import (
	"context"

	"mall-review-rpc/review"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                      = review.Empty
	GetProductRatingSummaryReq = review.GetProductRatingSummaryReq
	GetReviewReq               = review.GetReviewReq
	ListProductReviewsReq      = review.ListProductReviewsReq
	ListProductReviewsResp     = review.ListProductReviewsResp
	ListUserReviewsReq         = review.ListUserReviewsReq
	RatingSummary              = review.RatingSummary
	ReplyReviewReq             = review.ReplyReviewReq
	ReviewItem                 = review.ReviewItem
	SoftDeleteReviewReq        = review.SoftDeleteReviewReq
	SubmitFollowupReq          = review.SubmitFollowupReq
	SubmitReviewReq            = review.SubmitReviewReq
	SubmitReviewResp           = review.SubmitReviewResp

	Review interface {
		SubmitReview(ctx context.Context, in *SubmitReviewReq, opts ...grpc.CallOption) (*SubmitReviewResp, error)
		SubmitFollowup(ctx context.Context, in *SubmitFollowupReq, opts ...grpc.CallOption) (*Empty, error)
		GetReview(ctx context.Context, in *GetReviewReq, opts ...grpc.CallOption) (*ReviewItem, error)
		ListProductReviews(ctx context.Context, in *ListProductReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error)
		ListUserReviews(ctx context.Context, in *ListUserReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error)
		GetProductRatingSummary(ctx context.Context, in *GetProductRatingSummaryReq, opts ...grpc.CallOption) (*RatingSummary, error)
		ReplyReview(ctx context.Context, in *ReplyReviewReq, opts ...grpc.CallOption) (*Empty, error)
		SoftDeleteReview(ctx context.Context, in *SoftDeleteReviewReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultReview struct {
		cli zrpc.Client
	}
)

func NewReview(cli zrpc.Client) Review {
	return &defaultReview{
		cli: cli,
	}
}

func (m *defaultReview) SubmitReview(ctx context.Context, in *SubmitReviewReq, opts ...grpc.CallOption) (*SubmitReviewResp, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.SubmitReview(ctx, in, opts...)
}

func (m *defaultReview) SubmitFollowup(ctx context.Context, in *SubmitFollowupReq, opts ...grpc.CallOption) (*Empty, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.SubmitFollowup(ctx, in, opts...)
}

func (m *defaultReview) GetReview(ctx context.Context, in *GetReviewReq, opts ...grpc.CallOption) (*ReviewItem, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.GetReview(ctx, in, opts...)
}

func (m *defaultReview) ListProductReviews(ctx context.Context, in *ListProductReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.ListProductReviews(ctx, in, opts...)
}

func (m *defaultReview) ListUserReviews(ctx context.Context, in *ListUserReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.ListUserReviews(ctx, in, opts...)
}

func (m *defaultReview) GetProductRatingSummary(ctx context.Context, in *GetProductRatingSummaryReq, opts ...grpc.CallOption) (*RatingSummary, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.GetProductRatingSummary(ctx, in, opts...)
}

func (m *defaultReview) ReplyReview(ctx context.Context, in *ReplyReviewReq, opts ...grpc.CallOption) (*Empty, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.ReplyReview(ctx, in, opts...)
}

func (m *defaultReview) SoftDeleteReview(ctx context.Context, in *SoftDeleteReviewReq, opts ...grpc.CallOption) (*Empty, error) {
	client := review.NewReviewClient(m.cli.Conn())
	return client.SoftDeleteReview(ctx, in, opts...)
}
