// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	blacklistFieldNames          = builder.RawFieldNames(&Blacklist{})
	blacklistRows                = strings.Join(blacklistFieldNames, ",")
	blacklistRowsExpectAutoSet   = strings.Join(stringx.Remove(blacklistFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	blacklistRowsWithPlaceHolder = strings.Join(stringx.Remove(blacklistFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBlacklistIdPrefix                      = "cache:blacklist:id:"
	cacheBlacklistSubjectTypeSubjectValuePrefix = "cache:blacklist:subjectType:subjectValue:"
)

type (
	blacklistModel interface {
		Insert(ctx context.Context, data *Blacklist) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Blacklist, error)
		FindOneBySubjectTypeSubjectValue(ctx context.Context, subjectType string, subjectValue string) (*Blacklist, error)
		Update(ctx context.Context, data *Blacklist) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultBlacklistModel struct {
		sqlc.CachedConn
		table string
	}

	Blacklist struct {
		Id           uint64       `db:"id"`
		SubjectType  string       `db:"subject_type"` // user/ip/device
		SubjectValue string       `db:"subject_value"`
		Reason       string       `db:"reason"`
		ExpiresAt    sql.NullTime `db:"expires_at"`
		CreateTime   time.Time    `db:"create_time"`
		UpdateTime   time.Time    `db:"update_time"`
	}
)

func newBlacklistModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBlacklistModel {
	return &defaultBlacklistModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`blacklist`",
	}
}

func (m *defaultBlacklistModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	blacklistIdKey := fmt.Sprintf("%s%v", cacheBlacklistIdPrefix, id)
	blacklistSubjectTypeSubjectValueKey := fmt.Sprintf("%s%v:%v", cacheBlacklistSubjectTypeSubjectValuePrefix, data.SubjectType, data.SubjectValue)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, blacklistIdKey, blacklistSubjectTypeSubjectValueKey)
	return err
}

func (m *defaultBlacklistModel) FindOne(ctx context.Context, id uint64) (*Blacklist, error) {
	blacklistIdKey := fmt.Sprintf("%s%v", cacheBlacklistIdPrefix, id)
	var resp Blacklist
	err := m.QueryRowCtx(ctx, &resp, blacklistIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", blacklistRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlacklistModel) FindOneBySubjectTypeSubjectValue(ctx context.Context, subjectType string, subjectValue string) (*Blacklist, error) {
	blacklistSubjectTypeSubjectValueKey := fmt.Sprintf("%s%v:%v", cacheBlacklistSubjectTypeSubjectValuePrefix, subjectType, subjectValue)
	var resp Blacklist
	err := m.QueryRowIndexCtx(ctx, &resp, blacklistSubjectTypeSubjectValueKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `subject_type` = ? and `subject_value` = ? limit 1", blacklistRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, subjectType, subjectValue); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlacklistModel) Insert(ctx context.Context, data *Blacklist) (sql.Result, error) {
	blacklistIdKey := fmt.Sprintf("%s%v", cacheBlacklistIdPrefix, data.Id)
	blacklistSubjectTypeSubjectValueKey := fmt.Sprintf("%s%v:%v", cacheBlacklistSubjectTypeSubjectValuePrefix, data.SubjectType, data.SubjectValue)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, blacklistRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SubjectType, data.SubjectValue, data.Reason, data.ExpiresAt)
	}, blacklistIdKey, blacklistSubjectTypeSubjectValueKey)
	return ret, err
}

func (m *defaultBlacklistModel) Update(ctx context.Context, newData *Blacklist) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	blacklistIdKey := fmt.Sprintf("%s%v", cacheBlacklistIdPrefix, data.Id)
	blacklistSubjectTypeSubjectValueKey := fmt.Sprintf("%s%v:%v", cacheBlacklistSubjectTypeSubjectValuePrefix, data.SubjectType, data.SubjectValue)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, blacklistRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SubjectType, newData.SubjectValue, newData.Reason, newData.ExpiresAt, newData.Id)
	}, blacklistIdKey, blacklistSubjectTypeSubjectValueKey)
	return err
}

func (m *defaultBlacklistModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBlacklistIdPrefix, primary)
}

func (m *defaultBlacklistModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", blacklistRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBlacklistModel) tableName() string {
	return m.table
}
