// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	participationTokenFieldNames          = builder.RawFieldNames(&ParticipationToken{})
	participationTokenRows                = strings.Join(participationTokenFieldNames, ",")
	participationTokenRowsExpectAutoSet   = strings.Join(stringx.Remove(participationTokenFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	participationTokenRowsWithPlaceHolder = strings.Join(stringx.Remove(participationTokenFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheParticipationTokenIdPrefix  = "cache:participationToken:id:"
	cacheParticipationTokenJtiPrefix = "cache:participationToken:jti:"
)

type (
	participationTokenModel interface {
		Insert(ctx context.Context, data *ParticipationToken) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ParticipationToken, error)
		FindOneByJti(ctx context.Context, jti string) (*ParticipationToken, error)
		Update(ctx context.Context, data *ParticipationToken) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultParticipationTokenModel struct {
		sqlc.CachedConn
		table string
	}

	ParticipationToken struct {
		Id         uint64       `db:"id"`
		Jti        string       `db:"jti"`
		Subject    string       `db:"subject"`
		ActivityId int64        `db:"activity_id"`
		ExpiresAt  time.Time    `db:"expires_at"`
		UsedAt     sql.NullTime `db:"used_at"`
		CreateTime time.Time    `db:"create_time"`
	}
)

func newParticipationTokenModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultParticipationTokenModel {
	return &defaultParticipationTokenModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`participation_token`",
	}
}

func (m *defaultParticipationTokenModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	participationTokenIdKey := fmt.Sprintf("%s%v", cacheParticipationTokenIdPrefix, id)
	participationTokenJtiKey := fmt.Sprintf("%s%v", cacheParticipationTokenJtiPrefix, data.Jti)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, participationTokenIdKey, participationTokenJtiKey)
	return err
}

func (m *defaultParticipationTokenModel) FindOne(ctx context.Context, id uint64) (*ParticipationToken, error) {
	participationTokenIdKey := fmt.Sprintf("%s%v", cacheParticipationTokenIdPrefix, id)
	var resp ParticipationToken
	err := m.QueryRowCtx(ctx, &resp, participationTokenIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", participationTokenRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultParticipationTokenModel) FindOneByJti(ctx context.Context, jti string) (*ParticipationToken, error) {
	participationTokenJtiKey := fmt.Sprintf("%s%v", cacheParticipationTokenJtiPrefix, jti)
	var resp ParticipationToken
	err := m.QueryRowIndexCtx(ctx, &resp, participationTokenJtiKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `jti` = ? limit 1", participationTokenRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, jti); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultParticipationTokenModel) Insert(ctx context.Context, data *ParticipationToken) (sql.Result, error) {
	participationTokenIdKey := fmt.Sprintf("%s%v", cacheParticipationTokenIdPrefix, data.Id)
	participationTokenJtiKey := fmt.Sprintf("%s%v", cacheParticipationTokenJtiPrefix, data.Jti)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, participationTokenRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Jti, data.Subject, data.ActivityId, data.ExpiresAt, data.UsedAt)
	}, participationTokenIdKey, participationTokenJtiKey)
	return ret, err
}

func (m *defaultParticipationTokenModel) Update(ctx context.Context, newData *ParticipationToken) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	participationTokenIdKey := fmt.Sprintf("%s%v", cacheParticipationTokenIdPrefix, data.Id)
	participationTokenJtiKey := fmt.Sprintf("%s%v", cacheParticipationTokenJtiPrefix, data.Jti)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, participationTokenRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Jti, newData.Subject, newData.ActivityId, newData.ExpiresAt, newData.UsedAt, newData.Id)
	}, participationTokenIdKey, participationTokenJtiKey)
	return err
}

func (m *defaultParticipationTokenModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheParticipationTokenIdPrefix, primary)
}

func (m *defaultParticipationTokenModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", participationTokenRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultParticipationTokenModel) tableName() string {
	return m.table
}
