// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logistics.proto

package server

import (
	"context"

	"mall-logistics-rpc/internal/logic"
	"mall-logistics-rpc/internal/svc"
	"mall-logistics-rpc/logistics"
)

type LogisticsServer struct {
	svcCtx *svc.ServiceContext
	logistics.UnimplementedLogisticsServer
}

func NewLogisticsServer(svcCtx *svc.ServiceContext) *LogisticsServer {
	return &LogisticsServer{
		svcCtx: svcCtx,
	}
}

func (s *LogisticsServer) CreateShipment(ctx context.Context, in *logistics.CreateShipmentReq) (*logistics.CreateShipmentResp, error) {
	l := logic.NewCreateShipmentLogic(ctx, s.svcCtx)
	return l.CreateShipment(in)
}

func (s *LogisticsServer) ListShipmentsByOrder(ctx context.Context, in *logistics.ListShipmentsByOrderReq) (*logistics.ListShipmentsByOrderResp, error) {
	l := logic.NewListShipmentsByOrderLogic(ctx, s.svcCtx)
	return l.ListShipmentsByOrder(in)
}

func (s *LogisticsServer) GetShipment(ctx context.Context, in *logistics.GetShipmentReq) (*logistics.Shipment, error) {
	l := logic.NewGetShipmentLogic(ctx, s.svcCtx)
	return l.GetShipment(in)
}

func (s *LogisticsServer) IngestWebhookEvents(ctx context.Context, in *logistics.IngestWebhookEventsReq) (*logistics.Empty, error) {
	l := logic.NewIngestWebhookEventsLogic(ctx, s.svcCtx)
	return l.IngestWebhookEvents(in)
}

func (s *LogisticsServer) RetrySubscribe(ctx context.Context, in *logistics.RetrySubscribeReq) (*logistics.Empty, error) {
	l := logic.NewRetrySubscribeLogic(ctx, s.svcCtx)
	return l.RetrySubscribe(in)
}

func (s *LogisticsServer) InjectTrack(ctx context.Context, in *logistics.InjectTrackReq) (*logistics.Empty, error) {
	l := logic.NewInjectTrackLogic(ctx, s.svcCtx)
	return l.InjectTrack(in)
}

func (s *LogisticsServer) CreateFreightTemplate(ctx context.Context, in *logistics.CreateFreightTemplateReq) (*logistics.CreateFreightTemplateResp, error) {
	l := logic.NewCreateFreightTemplateLogic(ctx, s.svcCtx)
	return l.CreateFreightTemplate(in)
}

func (s *LogisticsServer) ListFreightTemplates(ctx context.Context, in *logistics.ListFreightTemplatesReq) (*logistics.ListFreightTemplatesResp, error) {
	l := logic.NewListFreightTemplatesLogic(ctx, s.svcCtx)
	return l.ListFreightTemplates(in)
}

func (s *LogisticsServer) GetFreightTemplate(ctx context.Context, in *logistics.IdReq) (*logistics.FreightTemplate, error) {
	l := logic.NewGetFreightTemplateLogic(ctx, s.svcCtx)
	return l.GetFreightTemplate(in)
}

func (s *LogisticsServer) UpdateFreightTemplate(ctx context.Context, in *logistics.UpdateFreightTemplateReq) (*logistics.Empty, error) {
	l := logic.NewUpdateFreightTemplateLogic(ctx, s.svcCtx)
	return l.UpdateFreightTemplate(in)
}

func (s *LogisticsServer) DeleteFreightTemplate(ctx context.Context, in *logistics.IdReq) (*logistics.Empty, error) {
	l := logic.NewDeleteFreightTemplateLogic(ctx, s.svcCtx)
	return l.DeleteFreightTemplate(in)
}
