// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: review.proto

package review

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Review_SubmitReview_FullMethodName            = "/review.Review/SubmitReview"
	Review_SubmitFollowup_FullMethodName          = "/review.Review/SubmitFollowup"
	Review_GetReview_FullMethodName               = "/review.Review/GetReview"
	Review_ListProductReviews_FullMethodName      = "/review.Review/ListProductReviews"
	Review_ListUserReviews_FullMethodName         = "/review.Review/ListUserReviews"
	Review_GetProductRatingSummary_FullMethodName = "/review.Review/GetProductRatingSummary"
	Review_ReplyReview_FullMethodName             = "/review.Review/ReplyReview"
	Review_SoftDeleteReview_FullMethodName        = "/review.Review/SoftDeleteReview"
)

// ReviewClient is the client API for Review service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewClient interface {
	SubmitReview(ctx context.Context, in *SubmitReviewReq, opts ...grpc.CallOption) (*SubmitReviewResp, error)
	SubmitFollowup(ctx context.Context, in *SubmitFollowupReq, opts ...grpc.CallOption) (*Empty, error)
	GetReview(ctx context.Context, in *GetReviewReq, opts ...grpc.CallOption) (*ReviewItem, error)
	ListProductReviews(ctx context.Context, in *ListProductReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error)
	ListUserReviews(ctx context.Context, in *ListUserReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error)
	GetProductRatingSummary(ctx context.Context, in *GetProductRatingSummaryReq, opts ...grpc.CallOption) (*RatingSummary, error)
	ReplyReview(ctx context.Context, in *ReplyReviewReq, opts ...grpc.CallOption) (*Empty, error)
	SoftDeleteReview(ctx context.Context, in *SoftDeleteReviewReq, opts ...grpc.CallOption) (*Empty, error)
}

type reviewClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewClient(cc grpc.ClientConnInterface) ReviewClient {
	return &reviewClient{cc}
}

func (c *reviewClient) SubmitReview(ctx context.Context, in *SubmitReviewReq, opts ...grpc.CallOption) (*SubmitReviewResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitReviewResp)
	err := c.cc.Invoke(ctx, Review_SubmitReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) SubmitFollowup(ctx context.Context, in *SubmitFollowupReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Review_SubmitFollowup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) GetReview(ctx context.Context, in *GetReviewReq, opts ...grpc.CallOption) (*ReviewItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewItem)
	err := c.cc.Invoke(ctx, Review_GetReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) ListProductReviews(ctx context.Context, in *ListProductReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductReviewsResp)
	err := c.cc.Invoke(ctx, Review_ListProductReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) ListUserReviews(ctx context.Context, in *ListUserReviewsReq, opts ...grpc.CallOption) (*ListProductReviewsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductReviewsResp)
	err := c.cc.Invoke(ctx, Review_ListUserReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) GetProductRatingSummary(ctx context.Context, in *GetProductRatingSummaryReq, opts ...grpc.CallOption) (*RatingSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingSummary)
	err := c.cc.Invoke(ctx, Review_GetProductRatingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) ReplyReview(ctx context.Context, in *ReplyReviewReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Review_ReplyReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) SoftDeleteReview(ctx context.Context, in *SoftDeleteReviewReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Review_SoftDeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServer is the server API for Review service.
// All implementations must embed UnimplementedReviewServer
// for forward compatibility.
type ReviewServer interface {
	SubmitReview(context.Context, *SubmitReviewReq) (*SubmitReviewResp, error)
	SubmitFollowup(context.Context, *SubmitFollowupReq) (*Empty, error)
	GetReview(context.Context, *GetReviewReq) (*ReviewItem, error)
	ListProductReviews(context.Context, *ListProductReviewsReq) (*ListProductReviewsResp, error)
	ListUserReviews(context.Context, *ListUserReviewsReq) (*ListProductReviewsResp, error)
	GetProductRatingSummary(context.Context, *GetProductRatingSummaryReq) (*RatingSummary, error)
	ReplyReview(context.Context, *ReplyReviewReq) (*Empty, error)
	SoftDeleteReview(context.Context, *SoftDeleteReviewReq) (*Empty, error)
	mustEmbedUnimplementedReviewServer()
}

// UnimplementedReviewServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewServer struct{}

func (UnimplementedReviewServer) SubmitReview(context.Context, *SubmitReviewReq) (*SubmitReviewResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitReview not implemented")
}
func (UnimplementedReviewServer) SubmitFollowup(context.Context, *SubmitFollowupReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFollowup not implemented")
}
func (UnimplementedReviewServer) GetReview(context.Context, *GetReviewReq) (*ReviewItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReview not implemented")
}
func (UnimplementedReviewServer) ListProductReviews(context.Context, *ListProductReviewsReq) (*ListProductReviewsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductReviews not implemented")
}
func (UnimplementedReviewServer) ListUserReviews(context.Context, *ListUserReviewsReq) (*ListProductReviewsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserReviews not implemented")
}
func (UnimplementedReviewServer) GetProductRatingSummary(context.Context, *GetProductRatingSummaryReq) (*RatingSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductRatingSummary not implemented")
}
func (UnimplementedReviewServer) ReplyReview(context.Context, *ReplyReviewReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplyReview not implemented")
}
func (UnimplementedReviewServer) SoftDeleteReview(context.Context, *SoftDeleteReviewReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SoftDeleteReview not implemented")
}
func (UnimplementedReviewServer) mustEmbedUnimplementedReviewServer() {}
func (UnimplementedReviewServer) testEmbeddedByValue()                {}

// UnsafeReviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewServer will
// result in compilation errors.
type UnsafeReviewServer interface {
	mustEmbedUnimplementedReviewServer()
}

func RegisterReviewServer(s grpc.ServiceRegistrar, srv ReviewServer) {
	// If the following call panics, it indicates UnimplementedReviewServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Review_ServiceDesc, srv)
}

func _Review_SubmitReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).SubmitReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_SubmitReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).SubmitReview(ctx, req.(*SubmitReviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_SubmitFollowup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFollowupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).SubmitFollowup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_SubmitFollowup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).SubmitFollowup(ctx, req.(*SubmitFollowupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_GetReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).GetReview(ctx, req.(*GetReviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_ListProductReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductReviewsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).ListProductReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_ListProductReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).ListProductReviews(ctx, req.(*ListProductReviewsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_ListUserReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserReviewsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).ListUserReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_ListUserReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).ListUserReviews(ctx, req.(*ListUserReviewsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_GetProductRatingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRatingSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).GetProductRatingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_GetProductRatingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).GetProductRatingSummary(ctx, req.(*GetProductRatingSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_ReplyReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyReviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).ReplyReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_ReplyReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).ReplyReview(ctx, req.(*ReplyReviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_SoftDeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftDeleteReviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).SoftDeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Review_SoftDeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).SoftDeleteReview(ctx, req.(*SoftDeleteReviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Review_ServiceDesc is the grpc.ServiceDesc for Review service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Review_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "review.Review",
	HandlerType: (*ReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitReview",
			Handler:    _Review_SubmitReview_Handler,
		},
		{
			MethodName: "SubmitFollowup",
			Handler:    _Review_SubmitFollowup_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _Review_GetReview_Handler,
		},
		{
			MethodName: "ListProductReviews",
			Handler:    _Review_ListProductReviews_Handler,
		},
		{
			MethodName: "ListUserReviews",
			Handler:    _Review_ListUserReviews_Handler,
		},
		{
			MethodName: "GetProductRatingSummary",
			Handler:    _Review_GetProductRatingSummary_Handler,
		},
		{
			MethodName: "ReplyReview",
			Handler:    _Review_ReplyReview_Handler,
		},
		{
			MethodName: "SoftDeleteReview",
			Handler:    _Review_SoftDeleteReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
