// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: risk.proto

package risk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Risk_IssueToken_FullMethodName          = "/risk.Risk/IssueToken"
	Risk_VerifyToken_FullMethodName         = "/risk.Risk/VerifyToken"
	Risk_CheckBlacklist_FullMethodName      = "/risk.Risk/CheckBlacklist"
	Risk_AddToBlacklist_FullMethodName      = "/risk.Risk/AddToBlacklist"
	Risk_RemoveFromBlacklist_FullMethodName = "/risk.Risk/RemoveFromBlacklist"
	Risk_RateLimit_FullMethodName           = "/risk.Risk/RateLimit"
	Risk_GetRiskScore_FullMethodName        = "/risk.Risk/GetRiskScore"
	Risk_RecordEvent_FullMethodName         = "/risk.Risk/RecordEvent"
)

// RiskClient is the client API for Risk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskClient interface {
	IssueToken(ctx context.Context, in *IssueTokenReq, opts ...grpc.CallOption) (*IssueTokenResp, error)
	VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
	CheckBlacklist(ctx context.Context, in *CheckBlacklistReq, opts ...grpc.CallOption) (*CheckBlacklistResp, error)
	AddToBlacklist(ctx context.Context, in *AddToBlacklistReq, opts ...grpc.CallOption) (*Empty, error)
	RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistReq, opts ...grpc.CallOption) (*Empty, error)
	RateLimit(ctx context.Context, in *RateLimitReq, opts ...grpc.CallOption) (*RateLimitResp, error)
	GetRiskScore(ctx context.Context, in *GetRiskScoreReq, opts ...grpc.CallOption) (*GetRiskScoreResp, error)
	RecordEvent(ctx context.Context, in *RecordEventReq, opts ...grpc.CallOption) (*Empty, error)
}

type riskClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskClient(cc grpc.ClientConnInterface) RiskClient {
	return &riskClient{cc}
}

func (c *riskClient) IssueToken(ctx context.Context, in *IssueTokenReq, opts ...grpc.CallOption) (*IssueTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResp)
	err := c.cc.Invoke(ctx, Risk_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResp)
	err := c.cc.Invoke(ctx, Risk_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) CheckBlacklist(ctx context.Context, in *CheckBlacklistReq, opts ...grpc.CallOption) (*CheckBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBlacklistResp)
	err := c.cc.Invoke(ctx, Risk_CheckBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Risk_AddToBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Risk_RemoveFromBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) RateLimit(ctx context.Context, in *RateLimitReq, opts ...grpc.CallOption) (*RateLimitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitResp)
	err := c.cc.Invoke(ctx, Risk_RateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) GetRiskScore(ctx context.Context, in *GetRiskScoreReq, opts ...grpc.CallOption) (*GetRiskScoreResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiskScoreResp)
	err := c.cc.Invoke(ctx, Risk_GetRiskScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskClient) RecordEvent(ctx context.Context, in *RecordEventReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Risk_RecordEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServer is the server API for Risk service.
// All implementations must embed UnimplementedRiskServer
// for forward compatibility.
type RiskServer interface {
	IssueToken(context.Context, *IssueTokenReq) (*IssueTokenResp, error)
	VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenResp, error)
	CheckBlacklist(context.Context, *CheckBlacklistReq) (*CheckBlacklistResp, error)
	AddToBlacklist(context.Context, *AddToBlacklistReq) (*Empty, error)
	RemoveFromBlacklist(context.Context, *RemoveFromBlacklistReq) (*Empty, error)
	RateLimit(context.Context, *RateLimitReq) (*RateLimitResp, error)
	GetRiskScore(context.Context, *GetRiskScoreReq) (*GetRiskScoreResp, error)
	RecordEvent(context.Context, *RecordEventReq) (*Empty, error)
	mustEmbedUnimplementedRiskServer()
}

// UnimplementedRiskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskServer struct{}

func (UnimplementedRiskServer) IssueToken(context.Context, *IssueTokenReq) (*IssueTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedRiskServer) VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedRiskServer) CheckBlacklist(context.Context, *CheckBlacklistReq) (*CheckBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBlacklist not implemented")
}
func (UnimplementedRiskServer) AddToBlacklist(context.Context, *AddToBlacklistReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (UnimplementedRiskServer) RemoveFromBlacklist(context.Context, *RemoveFromBlacklistReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (UnimplementedRiskServer) RateLimit(context.Context, *RateLimitReq) (*RateLimitResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RateLimit not implemented")
}
func (UnimplementedRiskServer) GetRiskScore(context.Context, *GetRiskScoreReq) (*GetRiskScoreResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRiskScore not implemented")
}
func (UnimplementedRiskServer) RecordEvent(context.Context, *RecordEventReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedRiskServer) mustEmbedUnimplementedRiskServer() {}
func (UnimplementedRiskServer) testEmbeddedByValue()              {}

// UnsafeRiskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServer will
// result in compilation errors.
type UnsafeRiskServer interface {
	mustEmbedUnimplementedRiskServer()
}

func RegisterRiskServer(s grpc.ServiceRegistrar, srv RiskServer) {
	// If the following call panics, it indicates UnimplementedRiskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Risk_ServiceDesc, srv)
}

func _Risk_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).IssueToken(ctx, req.(*IssueTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).VerifyToken(ctx, req.(*VerifyTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_CheckBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).CheckBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_CheckBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).CheckBlacklist(ctx, req.(*CheckBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_AddToBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).AddToBlacklist(ctx, req.(*AddToBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_RemoveFromBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).RemoveFromBlacklist(ctx, req.(*RemoveFromBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_RateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).RateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_RateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).RateLimit(ctx, req.(*RateLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_GetRiskScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).GetRiskScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_GetRiskScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).GetRiskScore(ctx, req.(*GetRiskScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Risk_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Risk_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServer).RecordEvent(ctx, req.(*RecordEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Risk_ServiceDesc is the grpc.ServiceDesc for Risk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Risk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.Risk",
	HandlerType: (*RiskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueToken",
			Handler:    _Risk_IssueToken_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _Risk_VerifyToken_Handler,
		},
		{
			MethodName: "CheckBlacklist",
			Handler:    _Risk_CheckBlacklist_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _Risk_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _Risk_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "RateLimit",
			Handler:    _Risk_RateLimit_Handler,
		},
		{
			MethodName: "GetRiskScore",
			Handler:    _Risk_GetRiskScore_Handler,
		},
		{
			MethodName: "RecordEvent",
			Handler:    _Risk_RecordEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk.proto",
}
