// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payment_CreatePayment_FullMethodName         = "/payment.Payment/CreatePayment"
	Payment_GetPayment_FullMethodName            = "/payment.Payment/GetPayment"
	Payment_UpdatePaymentStatus_FullMethodName   = "/payment.Payment/UpdatePaymentStatus"
	Payment_GetMerchantWallet_FullMethodName     = "/payment.Payment/GetMerchantWallet"
	Payment_CreditWallet_FullMethodName          = "/payment.Payment/CreditWallet"
	Payment_CreateWithdrawal_FullMethodName      = "/payment.Payment/CreateWithdrawal"
	Payment_ListWithdrawals_FullMethodName       = "/payment.Payment/ListWithdrawals"
	Payment_AdminHandleWithdrawal_FullMethodName = "/payment.Payment/AdminHandleWithdrawal"
	Payment_ListBillRecords_FullMethodName       = "/payment.Payment/ListBillRecords"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
	GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error)
	UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusReq, opts ...grpc.CallOption) (*UpdatePaymentStatusResp, error)
	// ===== P1 merchant wallet =====
	GetMerchantWallet(ctx context.Context, in *GetMerchantWalletReq, opts ...grpc.CallOption) (*MerchantWallet, error)
	CreditWallet(ctx context.Context, in *CreditWalletReq, opts ...grpc.CallOption) (*OkResp, error)
	CreateWithdrawal(ctx context.Context, in *CreateWithdrawalReq, opts ...grpc.CallOption) (*CreateWithdrawalResp, error)
	ListWithdrawals(ctx context.Context, in *ListWithdrawalsReq, opts ...grpc.CallOption) (*ListWithdrawalsResp, error)
	AdminHandleWithdrawal(ctx context.Context, in *AdminHandleWithdrawalReq, opts ...grpc.CallOption) (*OkResp, error)
	ListBillRecords(ctx context.Context, in *ListBillRecordsReq, opts ...grpc.CallOption) (*ListBillRecordsResp, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResp)
	err := c.cc.Invoke(ctx, Payment_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentResp)
	err := c.cc.Invoke(ctx, Payment_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusReq, opts ...grpc.CallOption) (*UpdatePaymentStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaymentStatusResp)
	err := c.cc.Invoke(ctx, Payment_UpdatePaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetMerchantWallet(ctx context.Context, in *GetMerchantWalletReq, opts ...grpc.CallOption) (*MerchantWallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantWallet)
	err := c.cc.Invoke(ctx, Payment_GetMerchantWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CreditWallet(ctx context.Context, in *CreditWalletReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, Payment_CreditWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CreateWithdrawal(ctx context.Context, in *CreateWithdrawalReq, opts ...grpc.CallOption) (*CreateWithdrawalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWithdrawalResp)
	err := c.cc.Invoke(ctx, Payment_CreateWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListWithdrawals(ctx context.Context, in *ListWithdrawalsReq, opts ...grpc.CallOption) (*ListWithdrawalsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWithdrawalsResp)
	err := c.cc.Invoke(ctx, Payment_ListWithdrawals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AdminHandleWithdrawal(ctx context.Context, in *AdminHandleWithdrawalReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, Payment_AdminHandleWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListBillRecords(ctx context.Context, in *ListBillRecordsReq, opts ...grpc.CallOption) (*ListBillRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBillRecordsResp)
	err := c.cc.Invoke(ctx, Payment_ListBillRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility.
type PaymentServer interface {
	CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentResp, error)
	GetPayment(context.Context, *GetPaymentReq) (*GetPaymentResp, error)
	UpdatePaymentStatus(context.Context, *UpdatePaymentStatusReq) (*UpdatePaymentStatusResp, error)
	// ===== P1 merchant wallet =====
	GetMerchantWallet(context.Context, *GetMerchantWalletReq) (*MerchantWallet, error)
	CreditWallet(context.Context, *CreditWalletReq) (*OkResp, error)
	CreateWithdrawal(context.Context, *CreateWithdrawalReq) (*CreateWithdrawalResp, error)
	ListWithdrawals(context.Context, *ListWithdrawalsReq) (*ListWithdrawalsResp, error)
	AdminHandleWithdrawal(context.Context, *AdminHandleWithdrawalReq) (*OkResp, error)
	ListBillRecords(context.Context, *ListBillRecordsReq) (*ListBillRecordsResp, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServer struct{}

func (UnimplementedPaymentServer) CreatePayment(context.Context, *CreatePaymentReq) (*CreatePaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentServer) GetPayment(context.Context, *GetPaymentReq) (*GetPaymentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentServer) UpdatePaymentStatus(context.Context, *UpdatePaymentStatusReq) (*UpdatePaymentStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePaymentStatus not implemented")
}
func (UnimplementedPaymentServer) GetMerchantWallet(context.Context, *GetMerchantWalletReq) (*MerchantWallet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchantWallet not implemented")
}
func (UnimplementedPaymentServer) CreditWallet(context.Context, *CreditWalletReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreditWallet not implemented")
}
func (UnimplementedPaymentServer) CreateWithdrawal(context.Context, *CreateWithdrawalReq) (*CreateWithdrawalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWithdrawal not implemented")
}
func (UnimplementedPaymentServer) ListWithdrawals(context.Context, *ListWithdrawalsReq) (*ListWithdrawalsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWithdrawals not implemented")
}
func (UnimplementedPaymentServer) AdminHandleWithdrawal(context.Context, *AdminHandleWithdrawalReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminHandleWithdrawal not implemented")
}
func (UnimplementedPaymentServer) ListBillRecords(context.Context, *ListBillRecordsReq) (*ListBillRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBillRecords not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}
func (UnimplementedPaymentServer) testEmbeddedByValue()                 {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	// If the following call panics, it indicates UnimplementedPaymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreatePayment(ctx, req.(*CreatePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetPayment(ctx, req.(*GetPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_UpdatePaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).UpdatePaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_UpdatePaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).UpdatePaymentStatus(ctx, req.(*UpdatePaymentStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetMerchantWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetMerchantWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetMerchantWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetMerchantWallet(ctx, req.(*GetMerchantWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CreditWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreditWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CreditWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreditWallet(ctx, req.(*CreditWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CreateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWithdrawalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CreateWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreateWithdrawal(ctx, req.(*CreateWithdrawalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListWithdrawals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawalsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListWithdrawals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListWithdrawals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListWithdrawals(ctx, req.(*ListWithdrawalsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AdminHandleWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminHandleWithdrawalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AdminHandleWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AdminHandleWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AdminHandleWithdrawal(ctx, req.(*AdminHandleWithdrawalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListBillRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBillRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListBillRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListBillRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListBillRecords(ctx, req.(*ListBillRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _Payment_CreatePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _Payment_GetPayment_Handler,
		},
		{
			MethodName: "UpdatePaymentStatus",
			Handler:    _Payment_UpdatePaymentStatus_Handler,
		},
		{
			MethodName: "GetMerchantWallet",
			Handler:    _Payment_GetMerchantWallet_Handler,
		},
		{
			MethodName: "CreditWallet",
			Handler:    _Payment_CreditWallet_Handler,
		},
		{
			MethodName: "CreateWithdrawal",
			Handler:    _Payment_CreateWithdrawal_Handler,
		},
		{
			MethodName: "ListWithdrawals",
			Handler:    _Payment_ListWithdrawals_Handler,
		},
		{
			MethodName: "AdminHandleWithdrawal",
			Handler:    _Payment_AdminHandleWithdrawal_Handler,
		},
		{
			MethodName: "ListBillRecords",
			Handler:    _Payment_ListBillRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/payment.proto",
}
