// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CartAddReq struct {
	ProductId int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

type CartItem struct {
	ProductId int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
	Selected  bool  `json:"selected"`
}

type CartListResp struct {
	Items []CartItem `json:"items"`
}

type CartRemoveReq struct {
	ProductId int64 `json:"productId"`
}

type CartUpdateQuantityReq struct {
	ProductId int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

type CreateOrderItem struct {
	ProductId   int64  `json:"productId"`
	ProductName string `json:"productName"`
	Price       int64  `json:"price"`
	Quantity    int32  `json:"quantity"`
}

type CreateOrderReq struct {
	Items []CreateOrderItem `json:"items"`
}

type CreateOrderResp struct {
	Id          int64  `json:"id"`
	OrderNo     string `json:"orderNo"`
	TotalAmount int64  `json:"totalAmount"`
}

type CreatePaymentReq struct {
	OrderNo string `json:"orderNo"`
	Amount  int64  `json:"amount"`
	PayType int32  `json:"payType"`
}

type CreatePaymentResp struct {
	Id        int64  `json:"id"`
	PaymentNo string `json:"paymentNo"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id    int64  `json:"id"`
	Token string `json:"token"`
}

type OrderDetailReq struct {
	Id int64 `path:"id"`
}

type OrderDetailResp struct {
	Id          int64             `json:"id"`
	OrderNo     string            `json:"orderNo"`
	UserId      int64             `json:"userId"`
	TotalAmount int64             `json:"totalAmount"`
	Status      int32             `json:"status"`
	Items       []CreateOrderItem `json:"items"`
	CreateTime  int64             `json:"createTime"`
}

type OrderListReq struct {
	Status   int32 `form:"status,optional"`
	Page     int32 `form:"page,optional"`
	PageSize int32 `form:"pageSize,optional"`
}

type OrderListResp struct {
	Orders []OrderDetailResp `json:"orders"`
	Total  int64             `json:"total"`
}

type PaymentStatusReq struct {
	Id int64 `path:"id"`
}

type PaymentStatusResp struct {
	Id        int64  `json:"id"`
	PaymentNo string `json:"paymentNo"`
	OrderNo   string `json:"orderNo"`
	Amount    int64  `json:"amount"`
	Status    int32  `json:"status"`
	PayType   int32  `json:"payType"`
	PayTime   int64  `json:"payTime"`
}

type ProductDetailReq struct {
	Id int64 `path:"id"`
}

type ProductDetailResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Stock       int64  `json:"stock"`
	CategoryId  int64  `json:"categoryId"`
	Images      string `json:"images"`
	Status      int32  `json:"status"`
	CreateTime  int64  `json:"createTime"`
}

type ProductListReq struct {
	CategoryId int64 `form:"categoryId,optional"`
	Page       int32 `form:"page,optional"`
	PageSize   int32 `form:"pageSize,optional"`
}

type ProductListResp struct {
	Products []ProductDetailResp `json:"products"`
	Total    int64               `json:"total"`
}

type ProductSearchReq struct {
	Keyword  string `form:"keyword"`
	Page     int32  `form:"page,optional"`
	PageSize int32  `form:"pageSize,optional"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

type RegisterResp struct {
	Id int64 `json:"id"`
}

type UpdateUserReq struct {
	Phone  string `json:"phone"`
	Avatar string `json:"avatar"`
}

type UserInfoResp struct {
	Id         int64  `json:"id"`
	Username   string `json:"username"`
	Phone      string `json:"phone"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"createTime"`
}
