// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: payment.proto

package paymentclient

import (
	"context"

	"mall-payment-rpc/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePaymentReq        = payment.CreatePaymentReq
	CreatePaymentResp       = payment.CreatePaymentResp
	GetPaymentReq           = payment.GetPaymentReq
	GetPaymentResp          = payment.GetPaymentResp
	UpdatePaymentStatusReq  = payment.UpdatePaymentStatusReq
	UpdatePaymentStatusResp = payment.UpdatePaymentStatusResp

	Payment interface {
		CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error)
		GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error)
		UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusReq, opts ...grpc.CallOption) (*UpdatePaymentStatusResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

func (m *defaultPayment) CreatePayment(ctx context.Context, in *CreatePaymentReq, opts ...grpc.CallOption) (*CreatePaymentResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

func (m *defaultPayment) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.GetPayment(ctx, in, opts...)
}

func (m *defaultPayment) UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusReq, opts ...grpc.CallOption) (*UpdatePaymentStatusResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.UpdatePaymentStatus(ctx, in, opts...)
}
