// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: logistics.proto

package logisticsclient

import (
	"context"

	"mall-logistics-rpc/logistics"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateShipmentReq        = logistics.CreateShipmentReq
	CreateShipmentResp       = logistics.CreateShipmentResp
	Empty                    = logistics.Empty
	GetShipmentReq           = logistics.GetShipmentReq
	IngestWebhookEventsReq   = logistics.IngestWebhookEventsReq
	InjectTrackReq           = logistics.InjectTrackReq
	ListShipmentsByOrderReq  = logistics.ListShipmentsByOrderReq
	ListShipmentsByOrderResp = logistics.ListShipmentsByOrderResp
	RetrySubscribeReq        = logistics.RetrySubscribeReq
	Shipment                 = logistics.Shipment

	Logistics interface {
		CreateShipment(ctx context.Context, in *CreateShipmentReq, opts ...grpc.CallOption) (*CreateShipmentResp, error)
		ListShipmentsByOrder(ctx context.Context, in *ListShipmentsByOrderReq, opts ...grpc.CallOption) (*ListShipmentsByOrderResp, error)
		GetShipment(ctx context.Context, in *GetShipmentReq, opts ...grpc.CallOption) (*Shipment, error)
		IngestWebhookEvents(ctx context.Context, in *IngestWebhookEventsReq, opts ...grpc.CallOption) (*Empty, error)
		RetrySubscribe(ctx context.Context, in *RetrySubscribeReq, opts ...grpc.CallOption) (*Empty, error)
		InjectTrack(ctx context.Context, in *InjectTrackReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultLogistics struct {
		cli zrpc.Client
	}
)

func NewLogistics(cli zrpc.Client) Logistics {
	return &defaultLogistics{
		cli: cli,
	}
}

func (m *defaultLogistics) CreateShipment(ctx context.Context, in *CreateShipmentReq, opts ...grpc.CallOption) (*CreateShipmentResp, error) {
	client := logistics.NewLogisticsClient(m.cli.Conn())
	return client.CreateShipment(ctx, in, opts...)
}

func (m *defaultLogistics) ListShipmentsByOrder(ctx context.Context, in *ListShipmentsByOrderReq, opts ...grpc.CallOption) (*ListShipmentsByOrderResp, error) {
	client := logistics.NewLogisticsClient(m.cli.Conn())
	return client.ListShipmentsByOrder(ctx, in, opts...)
}

func (m *defaultLogistics) GetShipment(ctx context.Context, in *GetShipmentReq, opts ...grpc.CallOption) (*Shipment, error) {
	client := logistics.NewLogisticsClient(m.cli.Conn())
	return client.GetShipment(ctx, in, opts...)
}

func (m *defaultLogistics) IngestWebhookEvents(ctx context.Context, in *IngestWebhookEventsReq, opts ...grpc.CallOption) (*Empty, error) {
	client := logistics.NewLogisticsClient(m.cli.Conn())
	return client.IngestWebhookEvents(ctx, in, opts...)
}

func (m *defaultLogistics) RetrySubscribe(ctx context.Context, in *RetrySubscribeReq, opts ...grpc.CallOption) (*Empty, error) {
	client := logistics.NewLogisticsClient(m.cli.Conn())
	return client.RetrySubscribe(ctx, in, opts...)
}

func (m *defaultLogistics) InjectTrack(ctx context.Context, in *InjectTrackReq, opts ...grpc.CallOption) (*Empty, error) {
	client := logistics.NewLogisticsClient(m.cli.Conn())
	return client.InjectTrack(ctx, in, opts...)
}
