// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowStepLogFieldNames          = builder.RawFieldNames(&WorkflowStepLog{})
	workflowStepLogRows                = strings.Join(workflowStepLogFieldNames, ",")
	workflowStepLogRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowStepLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowStepLogRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowStepLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWorkflowStepLogIdPrefix = "cache:workflowStepLog:id:"
)

type (
	workflowStepLogModel interface {
		Insert(ctx context.Context, data *WorkflowStepLog) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowStepLog, error)
		Update(ctx context.Context, data *WorkflowStepLog) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowStepLogModel struct {
		sqlc.CachedConn
		table string
	}

	WorkflowStepLog struct {
		Id         uint64    `db:"id"`
		InstanceId int64     `db:"instance_id"`
		FromState  string    `db:"from_state"`
		ToState    string    `db:"to_state"`
		Trigger    string    `db:"trigger"`
		LatencyMs  int64     `db:"latency_ms"`
		Error      string    `db:"error"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newWorkflowStepLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWorkflowStepLogModel {
	return &defaultWorkflowStepLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`workflow_step_log`",
	}
}

func (m *defaultWorkflowStepLogModel) Delete(ctx context.Context, id uint64) error {
	workflowStepLogIdKey := fmt.Sprintf("%s%v", cacheWorkflowStepLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, workflowStepLogIdKey)
	return err
}

func (m *defaultWorkflowStepLogModel) FindOne(ctx context.Context, id uint64) (*WorkflowStepLog, error) {
	workflowStepLogIdKey := fmt.Sprintf("%s%v", cacheWorkflowStepLogIdPrefix, id)
	var resp WorkflowStepLog
	err := m.QueryRowCtx(ctx, &resp, workflowStepLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowStepLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowStepLogModel) Insert(ctx context.Context, data *WorkflowStepLog) (sql.Result, error) {
	workflowStepLogIdKey := fmt.Sprintf("%s%v", cacheWorkflowStepLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, workflowStepLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.InstanceId, data.FromState, data.ToState, data.Trigger, data.LatencyMs, data.Error)
	}, workflowStepLogIdKey)
	return ret, err
}

func (m *defaultWorkflowStepLogModel) Update(ctx context.Context, data *WorkflowStepLog) error {
	workflowStepLogIdKey := fmt.Sprintf("%s%v", cacheWorkflowStepLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowStepLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.InstanceId, data.FromState, data.ToState, data.Trigger, data.LatencyMs, data.Error, data.Id)
	}, workflowStepLogIdKey)
	return err
}

func (m *defaultWorkflowStepLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWorkflowStepLogIdPrefix, primary)
}

func (m *defaultWorkflowStepLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowStepLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWorkflowStepLogModel) tableName() string {
	return m.table
}
