// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowDefinitionFieldNames          = builder.RawFieldNames(&WorkflowDefinition{})
	workflowDefinitionRows                = strings.Join(workflowDefinitionFieldNames, ",")
	workflowDefinitionRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowDefinitionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowDefinitionRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowDefinitionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWorkflowDefinitionIdPrefix   = "cache:workflowDefinition:id:"
	cacheWorkflowDefinitionCodePrefix = "cache:workflowDefinition:code:"
)

type (
	workflowDefinitionModel interface {
		Insert(ctx context.Context, data *WorkflowDefinition) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowDefinition, error)
		FindOneByCode(ctx context.Context, code string) (*WorkflowDefinition, error)
		Update(ctx context.Context, data *WorkflowDefinition) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowDefinitionModel struct {
		sqlc.CachedConn
		table string
	}

	WorkflowDefinition struct {
		Id              uint64    `db:"id"`
		Code            string    `db:"code"`
		Description     string    `db:"description"`
		StatesJson      string    `db:"states_json"`
		TransitionsJson string    `db:"transitions_json"`
		Version         int64     `db:"version"`
		Status          string    `db:"status"`
		CreateTime      time.Time `db:"create_time"`
		UpdateTime      time.Time `db:"update_time"`
	}
)

func newWorkflowDefinitionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWorkflowDefinitionModel {
	return &defaultWorkflowDefinitionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`workflow_definition`",
	}
}

func (m *defaultWorkflowDefinitionModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	workflowDefinitionCodeKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionCodePrefix, data.Code)
	workflowDefinitionIdKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, workflowDefinitionCodeKey, workflowDefinitionIdKey)
	return err
}

func (m *defaultWorkflowDefinitionModel) FindOne(ctx context.Context, id uint64) (*WorkflowDefinition, error) {
	workflowDefinitionIdKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionIdPrefix, id)
	var resp WorkflowDefinition
	err := m.QueryRowCtx(ctx, &resp, workflowDefinitionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowDefinitionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowDefinitionModel) FindOneByCode(ctx context.Context, code string) (*WorkflowDefinition, error) {
	workflowDefinitionCodeKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionCodePrefix, code)
	var resp WorkflowDefinition
	err := m.QueryRowIndexCtx(ctx, &resp, workflowDefinitionCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", workflowDefinitionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowDefinitionModel) Insert(ctx context.Context, data *WorkflowDefinition) (sql.Result, error) {
	workflowDefinitionCodeKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionCodePrefix, data.Code)
	workflowDefinitionIdKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, workflowDefinitionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Code, data.Description, data.StatesJson, data.TransitionsJson, data.Version, data.Status)
	}, workflowDefinitionCodeKey, workflowDefinitionIdKey)
	return ret, err
}

func (m *defaultWorkflowDefinitionModel) Update(ctx context.Context, newData *WorkflowDefinition) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	workflowDefinitionCodeKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionCodePrefix, data.Code)
	workflowDefinitionIdKey := fmt.Sprintf("%s%v", cacheWorkflowDefinitionIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowDefinitionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Code, newData.Description, newData.StatesJson, newData.TransitionsJson, newData.Version, newData.Status, newData.Id)
	}, workflowDefinitionCodeKey, workflowDefinitionIdKey)
	return err
}

func (m *defaultWorkflowDefinitionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWorkflowDefinitionIdPrefix, primary)
}

func (m *defaultWorkflowDefinitionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowDefinitionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWorkflowDefinitionModel) tableName() string {
	return m.table
}
