Name: product.rpc
ListenOn: 0.0.0.0:9002
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: product.rpc

DataSource: proxysql:proxysql123@tcp(127.0.0.1:6033)/mall_product?charset=utf8mb4&parseTime=true&loc=Local

Cache:
  - Host: 127.0.0.1:6379
