// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: shop/shop.proto

package shop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopService_GetShop_FullMethodName                    = "/shop.ShopService/GetShop"
	ShopService_ListShops_FullMethodName                  = "/shop.ShopService/ListShops"
	ShopService_ListRecommendedShops_FullMethodName       = "/shop.ShopService/ListRecommendedShops"
	ShopService_FollowShop_FullMethodName                 = "/shop.ShopService/FollowShop"
	ShopService_UnfollowShop_FullMethodName               = "/shop.ShopService/UnfollowShop"
	ShopService_IsFollowing_FullMethodName                = "/shop.ShopService/IsFollowing"
	ShopService_ListFollowedShops_FullMethodName          = "/shop.ShopService/ListFollowedShops"
	ShopService_CreateShop_FullMethodName                 = "/shop.ShopService/CreateShop"
	ShopService_UpdateShop_FullMethodName                 = "/shop.ShopService/UpdateShop"
	ShopService_IncrProductCount_FullMethodName           = "/shop.ShopService/IncrProductCount"
	ShopService_ApplyShop_FullMethodName                  = "/shop.ShopService/ApplyShop"
	ShopService_GetShopApplication_FullMethodName         = "/shop.ShopService/GetShopApplication"
	ShopService_ListShopApplications_FullMethodName       = "/shop.ShopService/ListShopApplications"
	ShopService_ReviewShopApplication_FullMethodName      = "/shop.ShopService/ReviewShopApplication"
	ShopService_GetShopByOwnerId_FullMethodName           = "/shop.ShopService/GetShopByOwnerId"
	ShopService_UpdateShopStatus_FullMethodName           = "/shop.ShopService/UpdateShopStatus"
	ShopService_AdjustCreditScore_FullMethodName          = "/shop.ShopService/AdjustCreditScore"
	ShopService_ListMyApplications_FullMethodName         = "/shop.ShopService/ListMyApplications"
	ShopService_ListShopLevels_FullMethodName             = "/shop.ShopService/ListShopLevels"
	ShopService_GetMyLevelStatus_FullMethodName           = "/shop.ShopService/GetMyLevelStatus"
	ShopService_SubmitLevelApplication_FullMethodName     = "/shop.ShopService/SubmitLevelApplication"
	ShopService_ListLevelApplications_FullMethodName      = "/shop.ShopService/ListLevelApplications"
	ShopService_ReviewLevelApplication_FullMethodName     = "/shop.ShopService/ReviewLevelApplication"
	ShopService_SubmitShopLifecycleRequest_FullMethodName = "/shop.ShopService/SubmitShopLifecycleRequest"
	ShopService_ListShopLifecycleRequests_FullMethodName  = "/shop.ShopService/ListShopLifecycleRequests"
	ShopService_ReviewShopLifecycleRequest_FullMethodName = "/shop.ShopService/ReviewShopLifecycleRequest"
)

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopServiceClient interface {
	GetShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*GetShopResp, error)
	ListShops(ctx context.Context, in *ListShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error)
	ListRecommendedShops(ctx context.Context, in *ListRecommendedShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error)
	FollowShop(ctx context.Context, in *FollowShopReq, opts ...grpc.CallOption) (*OkResp, error)
	UnfollowShop(ctx context.Context, in *UnfollowShopReq, opts ...grpc.CallOption) (*OkResp, error)
	IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error)
	ListFollowedShops(ctx context.Context, in *ListFollowedShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error)
	CreateShop(ctx context.Context, in *CreateShopReq, opts ...grpc.CallOption) (*CreateShopResp, error)
	UpdateShop(ctx context.Context, in *UpdateShopReq, opts ...grpc.CallOption) (*OkResp, error)
	IncrProductCount(ctx context.Context, in *IncrProductCountReq, opts ...grpc.CallOption) (*OkResp, error)
	ApplyShop(ctx context.Context, in *ApplyShopReq, opts ...grpc.CallOption) (*ApplyShopResp, error)
	GetShopApplication(ctx context.Context, in *GetShopApplicationReq, opts ...grpc.CallOption) (*ShopApplication, error)
	ListShopApplications(ctx context.Context, in *ListShopApplicationsReq, opts ...grpc.CallOption) (*ListShopApplicationsResp, error)
	ReviewShopApplication(ctx context.Context, in *ReviewShopApplicationReq, opts ...grpc.CallOption) (*OkResp, error)
	GetShopByOwnerId(ctx context.Context, in *GetShopByOwnerIdReq, opts ...grpc.CallOption) (*ShopDetailResp, error)
	UpdateShopStatus(ctx context.Context, in *UpdateShopStatusReq, opts ...grpc.CallOption) (*OkResp, error)
	AdjustCreditScore(ctx context.Context, in *AdjustCreditScoreReq, opts ...grpc.CallOption) (*OkResp, error)
	ListMyApplications(ctx context.Context, in *ListMyApplicationsReq, opts ...grpc.CallOption) (*ListShopApplicationsResp, error)
	// ===== B-5/B-6 Shop level system =====
	ListShopLevels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListShopLevelsResp, error)
	GetMyLevelStatus(ctx context.Context, in *GetMyLevelStatusReq, opts ...grpc.CallOption) (*MyLevelStatus, error)
	SubmitLevelApplication(ctx context.Context, in *SubmitLevelApplicationReq, opts ...grpc.CallOption) (*SubmitLevelApplicationResp, error)
	ListLevelApplications(ctx context.Context, in *ListLevelApplicationsReq, opts ...grpc.CallOption) (*ListLevelApplicationsResp, error)
	ReviewLevelApplication(ctx context.Context, in *ReviewLevelApplicationReq, opts ...grpc.CallOption) (*OkResp, error)
	// ===== B-4 Shop lifecycle (deactivate/pause/resume) =====
	SubmitShopLifecycleRequest(ctx context.Context, in *SubmitShopLifecycleRequestReq, opts ...grpc.CallOption) (*SubmitShopLifecycleRequestResp, error)
	ListShopLifecycleRequests(ctx context.Context, in *ListShopLifecycleRequestsReq, opts ...grpc.CallOption) (*ListShopLifecycleRequestsResp, error)
	ReviewShopLifecycleRequest(ctx context.Context, in *ReviewShopLifecycleRequestReq, opts ...grpc.CallOption) (*OkResp, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) GetShop(ctx context.Context, in *GetShopReq, opts ...grpc.CallOption) (*GetShopResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShopResp)
	err := c.cc.Invoke(ctx, ShopService_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListShops(ctx context.Context, in *ListShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopsResp)
	err := c.cc.Invoke(ctx, ShopService_ListShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListRecommendedShops(ctx context.Context, in *ListRecommendedShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopsResp)
	err := c.cc.Invoke(ctx, ShopService_ListRecommendedShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) FollowShop(ctx context.Context, in *FollowShopReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_FollowShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UnfollowShop(ctx context.Context, in *UnfollowShopReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_UnfollowShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowingResp)
	err := c.cc.Invoke(ctx, ShopService_IsFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListFollowedShops(ctx context.Context, in *ListFollowedShopsReq, opts ...grpc.CallOption) (*ListShopsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopsResp)
	err := c.cc.Invoke(ctx, ShopService_ListFollowedShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CreateShop(ctx context.Context, in *CreateShopReq, opts ...grpc.CallOption) (*CreateShopResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShopResp)
	err := c.cc.Invoke(ctx, ShopService_CreateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateShop(ctx context.Context, in *UpdateShopReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_UpdateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) IncrProductCount(ctx context.Context, in *IncrProductCountReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_IncrProductCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ApplyShop(ctx context.Context, in *ApplyShopReq, opts ...grpc.CallOption) (*ApplyShopResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyShopResp)
	err := c.cc.Invoke(ctx, ShopService_ApplyShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShopApplication(ctx context.Context, in *GetShopApplicationReq, opts ...grpc.CallOption) (*ShopApplication, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopApplication)
	err := c.cc.Invoke(ctx, ShopService_GetShopApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListShopApplications(ctx context.Context, in *ListShopApplicationsReq, opts ...grpc.CallOption) (*ListShopApplicationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopApplicationsResp)
	err := c.cc.Invoke(ctx, ShopService_ListShopApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ReviewShopApplication(ctx context.Context, in *ReviewShopApplicationReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_ReviewShopApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetShopByOwnerId(ctx context.Context, in *GetShopByOwnerIdReq, opts ...grpc.CallOption) (*ShopDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopDetailResp)
	err := c.cc.Invoke(ctx, ShopService_GetShopByOwnerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateShopStatus(ctx context.Context, in *UpdateShopStatusReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_UpdateShopStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) AdjustCreditScore(ctx context.Context, in *AdjustCreditScoreReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_AdjustCreditScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListMyApplications(ctx context.Context, in *ListMyApplicationsReq, opts ...grpc.CallOption) (*ListShopApplicationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopApplicationsResp)
	err := c.cc.Invoke(ctx, ShopService_ListMyApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListShopLevels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListShopLevelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopLevelsResp)
	err := c.cc.Invoke(ctx, ShopService_ListShopLevels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetMyLevelStatus(ctx context.Context, in *GetMyLevelStatusReq, opts ...grpc.CallOption) (*MyLevelStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyLevelStatus)
	err := c.cc.Invoke(ctx, ShopService_GetMyLevelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) SubmitLevelApplication(ctx context.Context, in *SubmitLevelApplicationReq, opts ...grpc.CallOption) (*SubmitLevelApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitLevelApplicationResp)
	err := c.cc.Invoke(ctx, ShopService_SubmitLevelApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListLevelApplications(ctx context.Context, in *ListLevelApplicationsReq, opts ...grpc.CallOption) (*ListLevelApplicationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLevelApplicationsResp)
	err := c.cc.Invoke(ctx, ShopService_ListLevelApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ReviewLevelApplication(ctx context.Context, in *ReviewLevelApplicationReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_ReviewLevelApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) SubmitShopLifecycleRequest(ctx context.Context, in *SubmitShopLifecycleRequestReq, opts ...grpc.CallOption) (*SubmitShopLifecycleRequestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitShopLifecycleRequestResp)
	err := c.cc.Invoke(ctx, ShopService_SubmitShopLifecycleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListShopLifecycleRequests(ctx context.Context, in *ListShopLifecycleRequestsReq, opts ...grpc.CallOption) (*ListShopLifecycleRequestsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopLifecycleRequestsResp)
	err := c.cc.Invoke(ctx, ShopService_ListShopLifecycleRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ReviewShopLifecycleRequest(ctx context.Context, in *ReviewShopLifecycleRequestReq, opts ...grpc.CallOption) (*OkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResp)
	err := c.cc.Invoke(ctx, ShopService_ReviewShopLifecycleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility.
type ShopServiceServer interface {
	GetShop(context.Context, *GetShopReq) (*GetShopResp, error)
	ListShops(context.Context, *ListShopsReq) (*ListShopsResp, error)
	ListRecommendedShops(context.Context, *ListRecommendedShopsReq) (*ListShopsResp, error)
	FollowShop(context.Context, *FollowShopReq) (*OkResp, error)
	UnfollowShop(context.Context, *UnfollowShopReq) (*OkResp, error)
	IsFollowing(context.Context, *IsFollowingReq) (*IsFollowingResp, error)
	ListFollowedShops(context.Context, *ListFollowedShopsReq) (*ListShopsResp, error)
	CreateShop(context.Context, *CreateShopReq) (*CreateShopResp, error)
	UpdateShop(context.Context, *UpdateShopReq) (*OkResp, error)
	IncrProductCount(context.Context, *IncrProductCountReq) (*OkResp, error)
	ApplyShop(context.Context, *ApplyShopReq) (*ApplyShopResp, error)
	GetShopApplication(context.Context, *GetShopApplicationReq) (*ShopApplication, error)
	ListShopApplications(context.Context, *ListShopApplicationsReq) (*ListShopApplicationsResp, error)
	ReviewShopApplication(context.Context, *ReviewShopApplicationReq) (*OkResp, error)
	GetShopByOwnerId(context.Context, *GetShopByOwnerIdReq) (*ShopDetailResp, error)
	UpdateShopStatus(context.Context, *UpdateShopStatusReq) (*OkResp, error)
	AdjustCreditScore(context.Context, *AdjustCreditScoreReq) (*OkResp, error)
	ListMyApplications(context.Context, *ListMyApplicationsReq) (*ListShopApplicationsResp, error)
	// ===== B-5/B-6 Shop level system =====
	ListShopLevels(context.Context, *Empty) (*ListShopLevelsResp, error)
	GetMyLevelStatus(context.Context, *GetMyLevelStatusReq) (*MyLevelStatus, error)
	SubmitLevelApplication(context.Context, *SubmitLevelApplicationReq) (*SubmitLevelApplicationResp, error)
	ListLevelApplications(context.Context, *ListLevelApplicationsReq) (*ListLevelApplicationsResp, error)
	ReviewLevelApplication(context.Context, *ReviewLevelApplicationReq) (*OkResp, error)
	// ===== B-4 Shop lifecycle (deactivate/pause/resume) =====
	SubmitShopLifecycleRequest(context.Context, *SubmitShopLifecycleRequestReq) (*SubmitShopLifecycleRequestResp, error)
	ListShopLifecycleRequests(context.Context, *ListShopLifecycleRequestsReq) (*ListShopLifecycleRequestsResp, error)
	ReviewShopLifecycleRequest(context.Context, *ReviewShopLifecycleRequestReq) (*OkResp, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopServiceServer struct{}

func (UnimplementedShopServiceServer) GetShop(context.Context, *GetShopReq) (*GetShopResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedShopServiceServer) ListShops(context.Context, *ListShopsReq) (*ListShopsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShops not implemented")
}
func (UnimplementedShopServiceServer) ListRecommendedShops(context.Context, *ListRecommendedShopsReq) (*ListShopsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecommendedShops not implemented")
}
func (UnimplementedShopServiceServer) FollowShop(context.Context, *FollowShopReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowShop not implemented")
}
func (UnimplementedShopServiceServer) UnfollowShop(context.Context, *UnfollowShopReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowShop not implemented")
}
func (UnimplementedShopServiceServer) IsFollowing(context.Context, *IsFollowingReq) (*IsFollowingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFollowing not implemented")
}
func (UnimplementedShopServiceServer) ListFollowedShops(context.Context, *ListFollowedShopsReq) (*ListShopsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowedShops not implemented")
}
func (UnimplementedShopServiceServer) CreateShop(context.Context, *CreateShopReq) (*CreateShopResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShop not implemented")
}
func (UnimplementedShopServiceServer) UpdateShop(context.Context, *UpdateShopReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShop not implemented")
}
func (UnimplementedShopServiceServer) IncrProductCount(context.Context, *IncrProductCountReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrProductCount not implemented")
}
func (UnimplementedShopServiceServer) ApplyShop(context.Context, *ApplyShopReq) (*ApplyShopResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyShop not implemented")
}
func (UnimplementedShopServiceServer) GetShopApplication(context.Context, *GetShopApplicationReq) (*ShopApplication, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopApplication not implemented")
}
func (UnimplementedShopServiceServer) ListShopApplications(context.Context, *ListShopApplicationsReq) (*ListShopApplicationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopApplications not implemented")
}
func (UnimplementedShopServiceServer) ReviewShopApplication(context.Context, *ReviewShopApplicationReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewShopApplication not implemented")
}
func (UnimplementedShopServiceServer) GetShopByOwnerId(context.Context, *GetShopByOwnerIdReq) (*ShopDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShopByOwnerId not implemented")
}
func (UnimplementedShopServiceServer) UpdateShopStatus(context.Context, *UpdateShopStatusReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShopStatus not implemented")
}
func (UnimplementedShopServiceServer) AdjustCreditScore(context.Context, *AdjustCreditScoreReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustCreditScore not implemented")
}
func (UnimplementedShopServiceServer) ListMyApplications(context.Context, *ListMyApplicationsReq) (*ListShopApplicationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyApplications not implemented")
}
func (UnimplementedShopServiceServer) ListShopLevels(context.Context, *Empty) (*ListShopLevelsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopLevels not implemented")
}
func (UnimplementedShopServiceServer) GetMyLevelStatus(context.Context, *GetMyLevelStatusReq) (*MyLevelStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyLevelStatus not implemented")
}
func (UnimplementedShopServiceServer) SubmitLevelApplication(context.Context, *SubmitLevelApplicationReq) (*SubmitLevelApplicationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitLevelApplication not implemented")
}
func (UnimplementedShopServiceServer) ListLevelApplications(context.Context, *ListLevelApplicationsReq) (*ListLevelApplicationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLevelApplications not implemented")
}
func (UnimplementedShopServiceServer) ReviewLevelApplication(context.Context, *ReviewLevelApplicationReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewLevelApplication not implemented")
}
func (UnimplementedShopServiceServer) SubmitShopLifecycleRequest(context.Context, *SubmitShopLifecycleRequestReq) (*SubmitShopLifecycleRequestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitShopLifecycleRequest not implemented")
}
func (UnimplementedShopServiceServer) ListShopLifecycleRequests(context.Context, *ListShopLifecycleRequestsReq) (*ListShopLifecycleRequestsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopLifecycleRequests not implemented")
}
func (UnimplementedShopServiceServer) ReviewShopLifecycleRequest(context.Context, *ReviewShopLifecycleRequestReq) (*OkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewShopLifecycleRequest not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}
func (UnimplementedShopServiceServer) testEmbeddedByValue()                     {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	// If the following call panics, it indicates UnimplementedShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShop(ctx, req.(*GetShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListShops(ctx, req.(*ListShopsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListRecommendedShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendedShopsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListRecommendedShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListRecommendedShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListRecommendedShops(ctx, req.(*ListRecommendedShopsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_FollowShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FollowShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_FollowShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FollowShop(ctx, req.(*FollowShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UnfollowShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UnfollowShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UnfollowShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UnfollowShop(ctx, req.(*UnfollowShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_IsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).IsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_IsFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).IsFollowing(ctx, req.(*IsFollowingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListFollowedShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowedShopsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListFollowedShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListFollowedShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListFollowedShops(ctx, req.(*ListFollowedShopsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateShop(ctx, req.(*CreateShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateShop(ctx, req.(*UpdateShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_IncrProductCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrProductCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).IncrProductCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_IncrProductCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).IncrProductCount(ctx, req.(*IncrProductCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ApplyShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyShopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ApplyShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ApplyShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ApplyShop(ctx, req.(*ApplyShopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShopApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShopApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShopApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShopApplication(ctx, req.(*GetShopApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListShopApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopApplicationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListShopApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListShopApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListShopApplications(ctx, req.(*ListShopApplicationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ReviewShopApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewShopApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ReviewShopApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ReviewShopApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ReviewShopApplication(ctx, req.(*ReviewShopApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetShopByOwnerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopByOwnerIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetShopByOwnerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetShopByOwnerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetShopByOwnerId(ctx, req.(*GetShopByOwnerIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateShopStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateShopStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateShopStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateShopStatus(ctx, req.(*UpdateShopStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_AdjustCreditScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustCreditScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).AdjustCreditScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_AdjustCreditScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).AdjustCreditScore(ctx, req.(*AdjustCreditScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListMyApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyApplicationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListMyApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListMyApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListMyApplications(ctx, req.(*ListMyApplicationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListShopLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListShopLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListShopLevels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListShopLevels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetMyLevelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyLevelStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetMyLevelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetMyLevelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetMyLevelStatus(ctx, req.(*GetMyLevelStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_SubmitLevelApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLevelApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).SubmitLevelApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_SubmitLevelApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).SubmitLevelApplication(ctx, req.(*SubmitLevelApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListLevelApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLevelApplicationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListLevelApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListLevelApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListLevelApplications(ctx, req.(*ListLevelApplicationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ReviewLevelApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewLevelApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ReviewLevelApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ReviewLevelApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ReviewLevelApplication(ctx, req.(*ReviewLevelApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_SubmitShopLifecycleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitShopLifecycleRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).SubmitShopLifecycleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_SubmitShopLifecycleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).SubmitShopLifecycleRequest(ctx, req.(*SubmitShopLifecycleRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListShopLifecycleRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopLifecycleRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListShopLifecycleRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListShopLifecycleRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListShopLifecycleRequests(ctx, req.(*ListShopLifecycleRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ReviewShopLifecycleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewShopLifecycleRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ReviewShopLifecycleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ReviewShopLifecycleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ReviewShopLifecycleRequest(ctx, req.(*ReviewShopLifecycleRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShop",
			Handler:    _ShopService_GetShop_Handler,
		},
		{
			MethodName: "ListShops",
			Handler:    _ShopService_ListShops_Handler,
		},
		{
			MethodName: "ListRecommendedShops",
			Handler:    _ShopService_ListRecommendedShops_Handler,
		},
		{
			MethodName: "FollowShop",
			Handler:    _ShopService_FollowShop_Handler,
		},
		{
			MethodName: "UnfollowShop",
			Handler:    _ShopService_UnfollowShop_Handler,
		},
		{
			MethodName: "IsFollowing",
			Handler:    _ShopService_IsFollowing_Handler,
		},
		{
			MethodName: "ListFollowedShops",
			Handler:    _ShopService_ListFollowedShops_Handler,
		},
		{
			MethodName: "CreateShop",
			Handler:    _ShopService_CreateShop_Handler,
		},
		{
			MethodName: "UpdateShop",
			Handler:    _ShopService_UpdateShop_Handler,
		},
		{
			MethodName: "IncrProductCount",
			Handler:    _ShopService_IncrProductCount_Handler,
		},
		{
			MethodName: "ApplyShop",
			Handler:    _ShopService_ApplyShop_Handler,
		},
		{
			MethodName: "GetShopApplication",
			Handler:    _ShopService_GetShopApplication_Handler,
		},
		{
			MethodName: "ListShopApplications",
			Handler:    _ShopService_ListShopApplications_Handler,
		},
		{
			MethodName: "ReviewShopApplication",
			Handler:    _ShopService_ReviewShopApplication_Handler,
		},
		{
			MethodName: "GetShopByOwnerId",
			Handler:    _ShopService_GetShopByOwnerId_Handler,
		},
		{
			MethodName: "UpdateShopStatus",
			Handler:    _ShopService_UpdateShopStatus_Handler,
		},
		{
			MethodName: "AdjustCreditScore",
			Handler:    _ShopService_AdjustCreditScore_Handler,
		},
		{
			MethodName: "ListMyApplications",
			Handler:    _ShopService_ListMyApplications_Handler,
		},
		{
			MethodName: "ListShopLevels",
			Handler:    _ShopService_ListShopLevels_Handler,
		},
		{
			MethodName: "GetMyLevelStatus",
			Handler:    _ShopService_GetMyLevelStatus_Handler,
		},
		{
			MethodName: "SubmitLevelApplication",
			Handler:    _ShopService_SubmitLevelApplication_Handler,
		},
		{
			MethodName: "ListLevelApplications",
			Handler:    _ShopService_ListLevelApplications_Handler,
		},
		{
			MethodName: "ReviewLevelApplication",
			Handler:    _ShopService_ReviewLevelApplication_Handler,
		},
		{
			MethodName: "SubmitShopLifecycleRequest",
			Handler:    _ShopService_SubmitShopLifecycleRequest_Handler,
		},
		{
			MethodName: "ListShopLifecycleRequests",
			Handler:    _ShopService_ListShopLifecycleRequests_Handler,
		},
		{
			MethodName: "ReviewShopLifecycleRequest",
			Handler:    _ShopService_ReviewShopLifecycleRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/shop.proto",
}
