// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: risk.proto

package server

import (
	"context"

	"mall-risk-rpc/internal/logic"
	"mall-risk-rpc/internal/svc"
	"mall-risk-rpc/risk"
)

type RiskServer struct {
	svcCtx *svc.ServiceContext
	risk.UnimplementedRiskServer
}

func NewRiskServer(svcCtx *svc.ServiceContext) *RiskServer {
	return &RiskServer{
		svcCtx: svcCtx,
	}
}

func (s *RiskServer) IssueToken(ctx context.Context, in *risk.IssueTokenReq) (*risk.IssueTokenResp, error) {
	l := logic.NewIssueTokenLogic(ctx, s.svcCtx)
	return l.IssueToken(in)
}

func (s *RiskServer) VerifyToken(ctx context.Context, in *risk.VerifyTokenReq) (*risk.VerifyTokenResp, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}

func (s *RiskServer) CheckBlacklist(ctx context.Context, in *risk.CheckBlacklistReq) (*risk.CheckBlacklistResp, error) {
	l := logic.NewCheckBlacklistLogic(ctx, s.svcCtx)
	return l.CheckBlacklist(in)
}

func (s *RiskServer) AddToBlacklist(ctx context.Context, in *risk.AddToBlacklistReq) (*risk.Empty, error) {
	l := logic.NewAddToBlacklistLogic(ctx, s.svcCtx)
	return l.AddToBlacklist(in)
}

func (s *RiskServer) RemoveFromBlacklist(ctx context.Context, in *risk.RemoveFromBlacklistReq) (*risk.Empty, error) {
	l := logic.NewRemoveFromBlacklistLogic(ctx, s.svcCtx)
	return l.RemoveFromBlacklist(in)
}

func (s *RiskServer) RateLimit(ctx context.Context, in *risk.RateLimitReq) (*risk.RateLimitResp, error) {
	l := logic.NewRateLimitLogic(ctx, s.svcCtx)
	return l.RateLimit(in)
}

func (s *RiskServer) GetRiskScore(ctx context.Context, in *risk.GetRiskScoreReq) (*risk.GetRiskScoreResp, error) {
	l := logic.NewGetRiskScoreLogic(ctx, s.svcCtx)
	return l.GetRiskScore(in)
}

func (s *RiskServer) RecordEvent(ctx context.Context, in *risk.RecordEventReq) (*risk.Empty, error) {
	l := logic.NewRecordEventLogic(ctx, s.svcCtx)
	return l.RecordEvent(in)
}
