// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: promotion/promotion.proto

package promotion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 通用 ==========
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_promotion_promotion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{0}
}

type OkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResp) Reset() {
	*x = OkResp{}
	mi := &file_promotion_promotion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResp) ProtoMessage() {}

func (x *OkResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResp.ProtoReflect.Descriptor instead.
func (*OkResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *OkResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ========== 活动 ==========
type ActivityTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // sku/category/shop/all
	TargetId      int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityTarget) Reset() {
	*x = ActivityTarget{}
	mi := &file_promotion_promotion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityTarget) ProtoMessage() {}

func (x *ActivityTarget) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityTarget.ProtoReflect.Descriptor instead.
func (*ActivityTarget) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityTarget) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityTarget) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityTarget) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ActivityTarget) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type ActivityAction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivityId     int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActionType     string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`          // reduce/discount/cash/fixprice/freeship/gift
	ThresholdType  string                 `protobuf:"bytes,4,opt,name=threshold_type,json=thresholdType,proto3" json:"threshold_type,omitempty"` // none/amount/quantity
	ThresholdValue int64                  `protobuf:"varint,5,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`
	BenefitValue   int64                  `protobuf:"varint,6,opt,name=benefit_value,json=benefitValue,proto3" json:"benefit_value,omitempty"`
	MaxDiscount    int64                  `protobuf:"varint,7,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	GiftSkuId      int64                  `protobuf:"varint,8,opt,name=gift_sku_id,json=giftSkuId,proto3" json:"gift_sku_id,omitempty"`
	StepOrder      int32                  `protobuf:"varint,9,opt,name=step_order,json=stepOrder,proto3" json:"step_order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivityAction) Reset() {
	*x = ActivityAction{}
	mi := &file_promotion_promotion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAction) ProtoMessage() {}

func (x *ActivityAction) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAction.ProtoReflect.Descriptor instead.
func (*ActivityAction) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityAction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityAction) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActivityAction) GetThresholdType() string {
	if x != nil {
		return x.ThresholdType
	}
	return ""
}

func (x *ActivityAction) GetThresholdValue() int64 {
	if x != nil {
		return x.ThresholdValue
	}
	return 0
}

func (x *ActivityAction) GetBenefitValue() int64 {
	if x != nil {
		return x.BenefitValue
	}
	return 0
}

func (x *ActivityAction) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *ActivityAction) GetGiftSkuId() int64 {
	if x != nil {
		return x.GiftSkuId
	}
	return 0
}

func (x *ActivityAction) GetStepOrder() int32 {
	if x != nil {
		return x.StepOrder
	}
	return 0
}

type ActivityRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerUserQuota  int32                  `protobuf:"varint,1,opt,name=per_user_quota,json=perUserQuota,proto3" json:"per_user_quota,omitempty"`    // 每人累计限购, 0=不限
	PerOrderQuota int32                  `protobuf:"varint,2,opt,name=per_order_quota,json=perOrderQuota,proto3" json:"per_order_quota,omitempty"` // 单订单限购件数, 0=不限
	PerDayQuota   int32                  `protobuf:"varint,3,opt,name=per_day_quota,json=perDayQuota,proto3" json:"per_day_quota,omitempty"`       // 每人每日限购, 0=不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityRule) Reset() {
	*x = ActivityRule{}
	mi := &file_promotion_promotion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRule) ProtoMessage() {}

func (x *ActivityRule) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRule.ProtoReflect.Descriptor instead.
func (*ActivityRule) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityRule) GetPerUserQuota() int32 {
	if x != nil {
		return x.PerUserQuota
	}
	return 0
}

func (x *ActivityRule) GetPerOrderQuota() int32 {
	if x != nil {
		return x.PerOrderQuota
	}
	return 0
}

func (x *ActivityRule) GetPerDayQuota() int32 {
	if x != nil {
		return x.PerDayQuota
	}
	return 0
}

type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // fullreduce/discount/fixprice/coupon
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShopId        int64                  `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 0草稿/1待开始/2进行中/3已结束/4已下线
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Stackable     bool                   `protobuf:"varint,9,opt,name=stackable,proto3" json:"stackable,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	CreateUserId  int64                  `protobuf:"varint,11,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Targets       []*ActivityTarget      `protobuf:"bytes,14,rep,name=targets,proto3" json:"targets,omitempty"`
	Actions       []*ActivityAction      `protobuf:"bytes,15,rep,name=actions,proto3" json:"actions,omitempty"`
	Rule          *ActivityRule          `protobuf:"bytes,16,opt,name=rule,proto3" json:"rule,omitempty"` // S2.4 限购规则, nil 表示不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_promotion_promotion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{5}
}

func (x *Activity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Activity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *Activity) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Activity) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Activity) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Activity) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Activity) GetStackable() bool {
	if x != nil {
		return x.Stackable
	}
	return false
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetCreateUserId() int64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *Activity) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Activity) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Activity) GetTargets() []*ActivityTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Activity) GetActions() []*ActivityAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Activity) GetRule() *ActivityRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CreateActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShopId        int64                  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Stackable     bool                   `protobuf:"varint,7,opt,name=stackable,proto3" json:"stackable,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreateUserId  int64                  `protobuf:"varint,9,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	Targets       []*ActivityTarget      `protobuf:"bytes,10,rep,name=targets,proto3" json:"targets,omitempty"`
	Actions       []*ActivityAction      `protobuf:"bytes,11,rep,name=actions,proto3" json:"actions,omitempty"`
	Rule          *ActivityRule          `protobuf:"bytes,12,opt,name=rule,proto3" json:"rule,omitempty"` // S2.4 限购, nil 不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityReq) Reset() {
	*x = CreateActivityReq{}
	mi := &file_promotion_promotion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityReq) ProtoMessage() {}

func (x *CreateActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityReq.ProtoReflect.Descriptor instead.
func (*CreateActivityReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{6}
}

func (x *CreateActivityReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateActivityReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateActivityReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CreateActivityReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateActivityReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateActivityReq) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateActivityReq) GetStackable() bool {
	if x != nil {
		return x.Stackable
	}
	return false
}

func (x *CreateActivityReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityReq) GetCreateUserId() int64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *CreateActivityReq) GetTargets() []*ActivityTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CreateActivityReq) GetActions() []*ActivityAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateActivityReq) GetRule() *ActivityRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CreateActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityResp) Reset() {
	*x = CreateActivityResp{}
	mi := &file_promotion_promotion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityResp) ProtoMessage() {}

func (x *CreateActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityResp.ProtoReflect.Descriptor instead.
func (*CreateActivityResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{7}
}

func (x *CreateActivityResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityReq) Reset() {
	*x = GetActivityReq{}
	mi := &file_promotion_promotion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityReq) ProtoMessage() {}

func (x *GetActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityReq.ProtoReflect.Descriptor instead.
func (*GetActivityReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{8}
}

func (x *GetActivityReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *Activity              `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityResp) Reset() {
	*x = GetActivityResp{}
	mi := &file_promotion_promotion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityResp) ProtoMessage() {}

func (x *GetActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityResp.ProtoReflect.Descriptor instead.
func (*GetActivityResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{9}
}

func (x *GetActivityResp) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type UpdateActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Stackable     bool                   `protobuf:"varint,6,opt,name=stackable,proto3" json:"stackable,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Targets       []*ActivityTarget      `protobuf:"bytes,8,rep,name=targets,proto3" json:"targets,omitempty"`
	Actions       []*ActivityAction      `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	Rule          *ActivityRule          `protobuf:"bytes,10,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityReq) Reset() {
	*x = UpdateActivityReq{}
	mi := &file_promotion_promotion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityReq) ProtoMessage() {}

func (x *UpdateActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityReq.ProtoReflect.Descriptor instead.
func (*UpdateActivityReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateActivityReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateActivityReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateActivityReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateActivityReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpdateActivityReq) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateActivityReq) GetStackable() bool {
	if x != nil {
		return x.Stackable
	}
	return false
}

func (x *UpdateActivityReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateActivityReq) GetTargets() []*ActivityTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *UpdateActivityReq) GetActions() []*ActivityAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *UpdateActivityReq) GetRule() *ActivityRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ChangeActivityStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeActivityStatusReq) Reset() {
	*x = ChangeActivityStatusReq{}
	mi := &file_promotion_promotion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeActivityStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeActivityStatusReq) ProtoMessage() {}

func (x *ChangeActivityStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeActivityStatusReq.ProtoReflect.Descriptor instead.
func (*ChangeActivityStatusReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeActivityStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeActivityStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListActivitiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`      // 空 = 全部
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // -1 = 全部
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesReq) Reset() {
	*x = ListActivitiesReq{}
	mi := &file_promotion_promotion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesReq) ProtoMessage() {}

func (x *ListActivitiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesReq.ProtoReflect.Descriptor instead.
func (*ListActivitiesReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{12}
}

func (x *ListActivitiesReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ListActivitiesReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListActivitiesReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListActivitiesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListActivitiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResp) Reset() {
	*x = ListActivitiesResp{}
	mi := &file_promotion_promotion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResp) ProtoMessage() {}

func (x *ListActivitiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResp.ProtoReflect.Descriptor instead.
func (*ListActivitiesResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{13}
}

func (x *ListActivitiesResp) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListActivitiesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ========== 券模板 ==========
type CouponTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // full_reduce/discount/cash/freeship
	Value         int64                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	MinAmount     int64                  `protobuf:"varint,7,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxDiscount   int64                  `protobuf:"varint,8,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	CategoryId    int64                  `protobuf:"varint,9,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalCount    int32                  `protobuf:"varint,10,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	ReceivedCount int32                  `protobuf:"varint,11,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	UsedCount     int32                  `protobuf:"varint,12,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	PerUserLimit  int32                  `protobuf:"varint,13,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`
	ValidType     int32                  `protobuf:"varint,14,opt,name=valid_type,json=validType,proto3" json:"valid_type,omitempty"` // 0固定日期/1领后N天
	ValidDays     int32                  `protobuf:"varint,15,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"`
	ValidStart    int64                  `protobuf:"varint,16,opt,name=valid_start,json=validStart,proto3" json:"valid_start,omitempty"`
	ValidEnd      int64                  `protobuf:"varint,17,opt,name=valid_end,json=validEnd,proto3" json:"valid_end,omitempty"`
	ReceiveStart  int64                  `protobuf:"varint,18,opt,name=receive_start,json=receiveStart,proto3" json:"receive_start,omitempty"`
	ReceiveEnd    int64                  `protobuf:"varint,19,opt,name=receive_end,json=receiveEnd,proto3" json:"receive_end,omitempty"`
	Status        int32                  `protobuf:"varint,20,opt,name=status,proto3" json:"status,omitempty"` // 0下架/1上架
	CreateTime    int64                  `protobuf:"varint,21,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,22,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// S2.3 新人券
	IsNewUserOnly     bool  `protobuf:"varint,23,opt,name=is_new_user_only,json=isNewUserOnly,proto3" json:"is_new_user_only,omitempty"`             // 仅新用户可领
	NewUserWithinDays int32 `protobuf:"varint,24,opt,name=new_user_within_days,json=newUserWithinDays,proto3" json:"new_user_within_days,omitempty"` // 注册后 N 天内算新用户 (默认 7)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CouponTemplate) Reset() {
	*x = CouponTemplate{}
	mi := &file_promotion_promotion_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponTemplate) ProtoMessage() {}

func (x *CouponTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponTemplate.ProtoReflect.Descriptor instead.
func (*CouponTemplate) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{14}
}

func (x *CouponTemplate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponTemplate) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CouponTemplate) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CouponTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponTemplate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CouponTemplate) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CouponTemplate) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CouponTemplate) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CouponTemplate) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CouponTemplate) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CouponTemplate) GetReceivedCount() int32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *CouponTemplate) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *CouponTemplate) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CouponTemplate) GetValidType() int32 {
	if x != nil {
		return x.ValidType
	}
	return 0
}

func (x *CouponTemplate) GetValidDays() int32 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CouponTemplate) GetValidStart() int64 {
	if x != nil {
		return x.ValidStart
	}
	return 0
}

func (x *CouponTemplate) GetValidEnd() int64 {
	if x != nil {
		return x.ValidEnd
	}
	return 0
}

func (x *CouponTemplate) GetReceiveStart() int64 {
	if x != nil {
		return x.ReceiveStart
	}
	return 0
}

func (x *CouponTemplate) GetReceiveEnd() int64 {
	if x != nil {
		return x.ReceiveEnd
	}
	return 0
}

func (x *CouponTemplate) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CouponTemplate) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CouponTemplate) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *CouponTemplate) GetIsNewUserOnly() bool {
	if x != nil {
		return x.IsNewUserOnly
	}
	return false
}

func (x *CouponTemplate) GetNewUserWithinDays() int32 {
	if x != nil {
		return x.NewUserWithinDays
	}
	return 0
}

type CreateCouponTemplateReq struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ShopId       int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type         string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value        int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	MinAmount    int64                  `protobuf:"varint,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxDiscount  int64                  `protobuf:"varint,6,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	CategoryId   int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalCount   int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PerUserLimit int32                  `protobuf:"varint,9,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`
	ValidType    int32                  `protobuf:"varint,10,opt,name=valid_type,json=validType,proto3" json:"valid_type,omitempty"`
	ValidDays    int32                  `protobuf:"varint,11,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"`
	ValidStart   int64                  `protobuf:"varint,12,opt,name=valid_start,json=validStart,proto3" json:"valid_start,omitempty"`
	ValidEnd     int64                  `protobuf:"varint,13,opt,name=valid_end,json=validEnd,proto3" json:"valid_end,omitempty"`
	ReceiveStart int64                  `protobuf:"varint,14,opt,name=receive_start,json=receiveStart,proto3" json:"receive_start,omitempty"`
	ReceiveEnd   int64                  `protobuf:"varint,15,opt,name=receive_end,json=receiveEnd,proto3" json:"receive_end,omitempty"`
	// S2.3 新人券
	IsNewUserOnly     bool  `protobuf:"varint,16,opt,name=is_new_user_only,json=isNewUserOnly,proto3" json:"is_new_user_only,omitempty"`
	NewUserWithinDays int32 `protobuf:"varint,17,opt,name=new_user_within_days,json=newUserWithinDays,proto3" json:"new_user_within_days,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCouponTemplateReq) Reset() {
	*x = CreateCouponTemplateReq{}
	mi := &file_promotion_promotion_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponTemplateReq) ProtoMessage() {}

func (x *CreateCouponTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponTemplateReq.ProtoReflect.Descriptor instead.
func (*CreateCouponTemplateReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCouponTemplateReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCouponTemplateReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCouponTemplateReq) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidType() int32 {
	if x != nil {
		return x.ValidType
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidDays() int32 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidStart() int64 {
	if x != nil {
		return x.ValidStart
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidEnd() int64 {
	if x != nil {
		return x.ValidEnd
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetReceiveStart() int64 {
	if x != nil {
		return x.ReceiveStart
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetReceiveEnd() int64 {
	if x != nil {
		return x.ReceiveEnd
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetIsNewUserOnly() bool {
	if x != nil {
		return x.IsNewUserOnly
	}
	return false
}

func (x *CreateCouponTemplateReq) GetNewUserWithinDays() int32 {
	if x != nil {
		return x.NewUserWithinDays
	}
	return 0
}

type CreateCouponTemplateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCouponTemplateResp) Reset() {
	*x = CreateCouponTemplateResp{}
	mi := &file_promotion_promotion_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponTemplateResp) ProtoMessage() {}

func (x *CreateCouponTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponTemplateResp.ProtoReflect.Descriptor instead.
func (*CreateCouponTemplateResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCouponTemplateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCouponTemplatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopId        int64                  `protobuf:"varint,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponTemplatesReq) Reset() {
	*x = ListCouponTemplatesReq{}
	mi := &file_promotion_promotion_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponTemplatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponTemplatesReq) ProtoMessage() {}

func (x *ListCouponTemplatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponTemplatesReq.ProtoReflect.Descriptor instead.
func (*ListCouponTemplatesReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{17}
}

func (x *ListCouponTemplatesReq) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ListCouponTemplatesReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListCouponTemplatesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCouponTemplatesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCouponTemplatesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*CouponTemplate      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponTemplatesResp) Reset() {
	*x = ListCouponTemplatesResp{}
	mi := &file_promotion_promotion_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponTemplatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponTemplatesResp) ProtoMessage() {}

func (x *ListCouponTemplatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponTemplatesResp.ProtoReflect.Descriptor instead.
func (*ListCouponTemplatesResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{18}
}

func (x *ListCouponTemplatesResp) GetTemplates() []*CouponTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListCouponTemplatesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChangeCouponTemplateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeCouponTemplateStatusReq) Reset() {
	*x = ChangeCouponTemplateStatusReq{}
	mi := &file_promotion_promotion_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeCouponTemplateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCouponTemplateStatusReq) ProtoMessage() {}

func (x *ChangeCouponTemplateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCouponTemplateStatusReq.ProtoReflect.Descriptor instead.
func (*ChangeCouponTemplateStatusReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{19}
}

func (x *ChangeCouponTemplateStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeCouponTemplateStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// ========== 用户券 ==========
type Coupon struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId  int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	UserId      int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId      int64                  `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Status      int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 0未用/1已锁定/2已使用/3已过期
	OrderId     int64                  `protobuf:"varint,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ReceiveTime int64                  `protobuf:"varint,7,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	ExpireTime  int64                  `protobuf:"varint,8,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	LockTime    int64                  `protobuf:"varint,9,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	UseTime     int64                  `protobuf:"varint,10,opt,name=use_time,json=useTime,proto3" json:"use_time,omitempty"`
	// 冗余 - 列表展示用
	TemplateName  string `protobuf:"bytes,11,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Type          string `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	Value         int64  `protobuf:"varint,13,opt,name=value,proto3" json:"value,omitempty"`
	MinAmount     int64  `protobuf:"varint,14,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	mi := &file_promotion_promotion_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{20}
}

func (x *Coupon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Coupon) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Coupon) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Coupon) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *Coupon) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Coupon) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Coupon) GetReceiveTime() int64 {
	if x != nil {
		return x.ReceiveTime
	}
	return 0
}

func (x *Coupon) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *Coupon) GetLockTime() int64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *Coupon) GetUseTime() int64 {
	if x != nil {
		return x.UseTime
	}
	return 0
}

func (x *Coupon) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *Coupon) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Coupon) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Coupon) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

type ReceiveCouponReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// S2.3 新人券校验: caller (mall-api) 查 user.create_time 后传入,
	// promotion-rpc 用此判断是否在 new_user_within_days 内
	UserRegisterTime int64 `protobuf:"varint,3,opt,name=user_register_time,json=userRegisterTime,proto3" json:"user_register_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReceiveCouponReq) Reset() {
	*x = ReceiveCouponReq{}
	mi := &file_promotion_promotion_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCouponReq) ProtoMessage() {}

func (x *ReceiveCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCouponReq.ProtoReflect.Descriptor instead.
func (*ReceiveCouponReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{21}
}

func (x *ReceiveCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReceiveCouponReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *ReceiveCouponReq) GetUserRegisterTime() int64 {
	if x != nil {
		return x.UserRegisterTime
	}
	return 0
}

type ReceiveCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCouponResp) Reset() {
	*x = ReceiveCouponResp{}
	mi := &file_promotion_promotion_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCouponResp) ProtoMessage() {}

func (x *ReceiveCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCouponResp.ProtoReflect.Descriptor instead.
func (*ReceiveCouponResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{22}
}

func (x *ReceiveCouponResp) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

type ListMyCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyCouponsReq) Reset() {
	*x = ListMyCouponsReq{}
	mi := &file_promotion_promotion_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyCouponsReq) ProtoMessage() {}

func (x *ListMyCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyCouponsReq.ProtoReflect.Descriptor instead.
func (*ListMyCouponsReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{23}
}

func (x *ListMyCouponsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMyCouponsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListMyCouponsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyCouponsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMyCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*Coupon              `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyCouponsResp) Reset() {
	*x = ListMyCouponsResp{}
	mi := &file_promotion_promotion_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyCouponsResp) ProtoMessage() {}

func (x *ListMyCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyCouponsResp.ProtoReflect.Descriptor instead.
func (*ListMyCouponsResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{24}
}

func (x *ListMyCouponsResp) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListMyCouponsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ========== 价格计算 (★) ==========
type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	OriginalPrice int64                  `protobuf:"varint,5,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_promotion_promotion_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{25}
}

func (x *CartItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItem) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CartItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CartItem) GetOriginalPrice() int64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PriceConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceConflict) Reset() {
	*x = PriceConflict{}
	mi := &file_promotion_promotion_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceConflict) ProtoMessage() {}

func (x *PriceConflict) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceConflict.ProtoReflect.Descriptor instead.
func (*PriceConflict) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{26}
}

func (x *PriceConflict) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *PriceConflict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CalcPriceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CouponIds     []int64                `protobuf:"varint,3,rep,packed,name=coupon_ids,json=couponIds,proto3" json:"coupon_ids,omitempty"`
	ShippingFee   int64                  `protobuf:"varint,4,opt,name=shipping_fee,json=shippingFee,proto3" json:"shipping_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcPriceReq) Reset() {
	*x = CalcPriceReq{}
	mi := &file_promotion_promotion_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcPriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcPriceReq) ProtoMessage() {}

func (x *CalcPriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcPriceReq.ProtoReflect.Descriptor instead.
func (*CalcPriceReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{27}
}

func (x *CalcPriceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CalcPriceReq) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CalcPriceReq) GetCouponIds() []int64 {
	if x != nil {
		return x.CouponIds
	}
	return nil
}

func (x *CalcPriceReq) GetShippingFee() int64 {
	if x != nil {
		return x.ShippingFee
	}
	return 0
}

type CalcPriceResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount       int64                  `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PromotionDiscount int64                  `protobuf:"varint,2,opt,name=promotion_discount,json=promotionDiscount,proto3" json:"promotion_discount,omitempty"`
	CouponDiscount    int64                  `protobuf:"varint,3,opt,name=coupon_discount,json=couponDiscount,proto3" json:"coupon_discount,omitempty"`
	ShippingFee       int64                  `protobuf:"varint,4,opt,name=shipping_fee,json=shippingFee,proto3" json:"shipping_fee,omitempty"`
	PaidAmount        int64                  `protobuf:"varint,5,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	DiscountDetail    string                 `protobuf:"bytes,6,opt,name=discount_detail,json=discountDetail,proto3" json:"discount_detail,omitempty"`
	Conflicts         []*PriceConflict       `protobuf:"bytes,7,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalcPriceResp) Reset() {
	*x = CalcPriceResp{}
	mi := &file_promotion_promotion_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcPriceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcPriceResp) ProtoMessage() {}

func (x *CalcPriceResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcPriceResp.ProtoReflect.Descriptor instead.
func (*CalcPriceResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{28}
}

func (x *CalcPriceResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CalcPriceResp) GetPromotionDiscount() int64 {
	if x != nil {
		return x.PromotionDiscount
	}
	return 0
}

func (x *CalcPriceResp) GetCouponDiscount() int64 {
	if x != nil {
		return x.CouponDiscount
	}
	return 0
}

func (x *CalcPriceResp) GetShippingFee() int64 {
	if x != nil {
		return x.ShippingFee
	}
	return 0
}

func (x *CalcPriceResp) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *CalcPriceResp) GetDiscountDetail() string {
	if x != nil {
		return x.DiscountDetail
	}
	return ""
}

func (x *CalcPriceResp) GetConflicts() []*PriceConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

// ========== 订单生命周期 ==========
type LockCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CouponIds     []int64                `protobuf:"varint,3,rep,packed,name=coupon_ids,json=couponIds,proto3" json:"coupon_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockCouponReq) Reset() {
	*x = LockCouponReq{}
	mi := &file_promotion_promotion_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockCouponReq) ProtoMessage() {}

func (x *LockCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockCouponReq.ProtoReflect.Descriptor instead.
func (*LockCouponReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{29}
}

func (x *LockCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *LockCouponReq) GetCouponIds() []int64 {
	if x != nil {
		return x.CouponIds
	}
	return nil
}

type ReleaseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCouponReq) Reset() {
	*x = ReleaseCouponReq{}
	mi := &file_promotion_promotion_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCouponReq) ProtoMessage() {}

func (x *ReleaseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCouponReq.ProtoReflect.Descriptor instead.
func (*ReleaseCouponReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{30}
}

func (x *ReleaseCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ConsumeCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeCouponReq) Reset() {
	*x = ConsumeCouponReq{}
	mi := &file_promotion_promotion_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeCouponReq) ProtoMessage() {}

func (x *ConsumeCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeCouponReq.ProtoReflect.Descriptor instead.
func (*ConsumeCouponReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{31}
}

func (x *ConsumeCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// ========== 退款分摊 ==========
type RefundItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundItem) Reset() {
	*x = RefundItem{}
	mi := &file_promotion_promotion_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundItem) ProtoMessage() {}

func (x *RefundItem) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundItem.ProtoReflect.Descriptor instead.
func (*RefundItem) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{32}
}

func (x *RefundItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *RefundItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CalcRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FullRefund    bool                   `protobuf:"varint,2,opt,name=full_refund,json=fullRefund,proto3" json:"full_refund,omitempty"`
	Items         []*RefundItem          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRefundReq) Reset() {
	*x = CalcRefundReq{}
	mi := &file_promotion_promotion_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRefundReq) ProtoMessage() {}

func (x *CalcRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRefundReq.ProtoReflect.Descriptor instead.
func (*CalcRefundReq) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{33}
}

func (x *CalcRefundReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CalcRefundReq) GetFullRefund() bool {
	if x != nil {
		return x.FullRefund
	}
	return false
}

func (x *CalcRefundReq) GetItems() []*RefundItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CalcRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundAmount  int64                  `protobuf:"varint,1,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	RefundDetail  string                 `protobuf:"bytes,2,opt,name=refund_detail,json=refundDetail,proto3" json:"refund_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRefundResp) Reset() {
	*x = CalcRefundResp{}
	mi := &file_promotion_promotion_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRefundResp) ProtoMessage() {}

func (x *CalcRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_promotion_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRefundResp.ProtoReflect.Descriptor instead.
func (*CalcRefundResp) Descriptor() ([]byte, []int) {
	return file_promotion_promotion_proto_rawDescGZIP(), []int{34}
}

func (x *CalcRefundResp) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *CalcRefundResp) GetRefundDetail() string {
	if x != nil {
		return x.RefundDetail
	}
	return ""
}

var File_promotion_promotion_proto protoreflect.FileDescriptor

const file_promotion_promotion_proto_rawDesc = "" +
	"\n" +
	"\x19promotion/promotion.proto\x12\tpromotion\"\a\n" +
	"\x05Empty\"\x18\n" +
	"\x06OkResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x7f\n" +
	"\x0eActivityTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\"\xb9\x02\n" +
	"\x0eActivityAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12%\n" +
	"\x0ethreshold_type\x18\x04 \x01(\tR\rthresholdType\x12'\n" +
	"\x0fthreshold_value\x18\x05 \x01(\x03R\x0ethresholdValue\x12#\n" +
	"\rbenefit_value\x18\x06 \x01(\x03R\fbenefitValue\x12!\n" +
	"\fmax_discount\x18\a \x01(\x03R\vmaxDiscount\x12\x1e\n" +
	"\vgift_sku_id\x18\b \x01(\x03R\tgiftSkuId\x12\x1d\n" +
	"\n" +
	"step_order\x18\t \x01(\x05R\tstepOrder\"\x80\x01\n" +
	"\fActivityRule\x12$\n" +
	"\x0eper_user_quota\x18\x01 \x01(\x05R\fperUserQuota\x12&\n" +
	"\x0fper_order_quota\x18\x02 \x01(\x05R\rperOrderQuota\x12\"\n" +
	"\rper_day_quota\x18\x03 \x01(\x05R\vperDayQuota\"\x88\x04\n" +
	"\bActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\x03R\x06shopId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x1c\n" +
	"\tstackable\x18\t \x01(\bR\tstackable\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12$\n" +
	"\x0ecreate_user_id\x18\v \x01(\x03R\fcreateUserId\x12\x1f\n" +
	"\vcreate_time\x18\f \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\r \x01(\x03R\n" +
	"updateTime\x123\n" +
	"\atargets\x18\x0e \x03(\v2\x19.promotion.ActivityTargetR\atargets\x123\n" +
	"\aactions\x18\x0f \x03(\v2\x19.promotion.ActivityActionR\aactions\x12+\n" +
	"\x04rule\x18\x10 \x01(\v2\x17.promotion.ActivityRuleR\x04rule\"\xa7\x03\n" +
	"\x11CreateActivityReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\x03R\x06shopId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1c\n" +
	"\tstackable\x18\a \x01(\bR\tstackable\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12$\n" +
	"\x0ecreate_user_id\x18\t \x01(\x03R\fcreateUserId\x123\n" +
	"\atargets\x18\n" +
	" \x03(\v2\x19.promotion.ActivityTargetR\atargets\x123\n" +
	"\aactions\x18\v \x03(\v2\x19.promotion.ActivityActionR\aactions\x12+\n" +
	"\x04rule\x18\f \x01(\v2\x17.promotion.ActivityRuleR\x04rule\"$\n" +
	"\x12CreateActivityResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x0eGetActivityReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x0fGetActivityResp\x12/\n" +
	"\bactivity\x18\x01 \x01(\v2\x13.promotion.ActivityR\bactivity\"\xe4\x02\n" +
	"\x11UpdateActivityReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1c\n" +
	"\tstackable\x18\x06 \x01(\bR\tstackable\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x123\n" +
	"\atargets\x18\b \x03(\v2\x19.promotion.ActivityTargetR\atargets\x123\n" +
	"\aactions\x18\t \x03(\v2\x19.promotion.ActivityActionR\aactions\x12+\n" +
	"\x04rule\x18\n" +
	" \x01(\v2\x17.promotion.ActivityRuleR\x04rule\"A\n" +
	"\x17ChangeActivityStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x89\x01\n" +
	"\x11ListActivitiesReq\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"_\n" +
	"\x12ListActivitiesResp\x123\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x13.promotion.ActivityR\n" +
	"activities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xfe\x05\n" +
	"\x0eCouponTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\x03R\x06shopId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\a \x01(\x03R\tminAmount\x12!\n" +
	"\fmax_discount\x18\b \x01(\x03R\vmaxDiscount\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\x03R\n" +
	"categoryId\x12\x1f\n" +
	"\vtotal_count\x18\n" +
	" \x01(\x05R\n" +
	"totalCount\x12%\n" +
	"\x0ereceived_count\x18\v \x01(\x05R\rreceivedCount\x12\x1d\n" +
	"\n" +
	"used_count\x18\f \x01(\x05R\tusedCount\x12$\n" +
	"\x0eper_user_limit\x18\r \x01(\x05R\fperUserLimit\x12\x1d\n" +
	"\n" +
	"valid_type\x18\x0e \x01(\x05R\tvalidType\x12\x1d\n" +
	"\n" +
	"valid_days\x18\x0f \x01(\x05R\tvalidDays\x12\x1f\n" +
	"\vvalid_start\x18\x10 \x01(\x03R\n" +
	"validStart\x12\x1b\n" +
	"\tvalid_end\x18\x11 \x01(\x03R\bvalidEnd\x12#\n" +
	"\rreceive_start\x18\x12 \x01(\x03R\freceiveStart\x12\x1f\n" +
	"\vreceive_end\x18\x13 \x01(\x03R\n" +
	"receiveEnd\x12\x16\n" +
	"\x06status\x18\x14 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x15 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x16 \x01(\x03R\n" +
	"updateTime\x12'\n" +
	"\x10is_new_user_only\x18\x17 \x01(\bR\risNewUserOnly\x12/\n" +
	"\x14new_user_within_days\x18\x18 \x01(\x05R\x11newUserWithinDays\"\xb6\x04\n" +
	"\x17CreateCouponTemplateReq\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x03R\tminAmount\x12!\n" +
	"\fmax_discount\x18\x06 \x01(\x03R\vmaxDiscount\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12$\n" +
	"\x0eper_user_limit\x18\t \x01(\x05R\fperUserLimit\x12\x1d\n" +
	"\n" +
	"valid_type\x18\n" +
	" \x01(\x05R\tvalidType\x12\x1d\n" +
	"\n" +
	"valid_days\x18\v \x01(\x05R\tvalidDays\x12\x1f\n" +
	"\vvalid_start\x18\f \x01(\x03R\n" +
	"validStart\x12\x1b\n" +
	"\tvalid_end\x18\r \x01(\x03R\bvalidEnd\x12#\n" +
	"\rreceive_start\x18\x0e \x01(\x03R\freceiveStart\x12\x1f\n" +
	"\vreceive_end\x18\x0f \x01(\x03R\n" +
	"receiveEnd\x12'\n" +
	"\x10is_new_user_only\x18\x10 \x01(\bR\risNewUserOnly\x12/\n" +
	"\x14new_user_within_days\x18\x11 \x01(\x05R\x11newUserWithinDays\"*\n" +
	"\x18CreateCouponTemplateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"z\n" +
	"\x16ListCouponTemplatesReq\x12\x17\n" +
	"\ashop_id\x18\x01 \x01(\x03R\x06shopId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"h\n" +
	"\x17ListCouponTemplatesResp\x127\n" +
	"\ttemplates\x18\x01 \x03(\v2\x19.promotion.CouponTemplateR\ttemplates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"G\n" +
	"\x1dChangeCouponTemplateStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x88\x03\n" +
	"\x06Coupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\x03R\x06shopId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x19\n" +
	"\border_id\x18\x06 \x01(\x03R\aorderId\x12!\n" +
	"\freceive_time\x18\a \x01(\x03R\vreceiveTime\x12\x1f\n" +
	"\vexpire_time\x18\b \x01(\x03R\n" +
	"expireTime\x12\x1b\n" +
	"\tlock_time\x18\t \x01(\x03R\blockTime\x12\x19\n" +
	"\buse_time\x18\n" +
	" \x01(\x03R\auseTime\x12#\n" +
	"\rtemplate_name\x18\v \x01(\tR\ftemplateName\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\r \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x0e \x01(\x03R\tminAmount\"z\n" +
	"\x10ReceiveCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\x12,\n" +
	"\x12user_register_time\x18\x03 \x01(\x03R\x10userRegisterTime\"0\n" +
	"\x11ReceiveCouponResp\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\"t\n" +
	"\x10ListMyCouponsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"V\n" +
	"\x11ListMyCouponsResp\x12+\n" +
	"\acoupons\x18\x01 \x03(\v2\x11.promotion.CouponR\acoupons\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbd\x01\n" +
	"\bCartItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x17\n" +
	"\ashop_id\x18\x03 \x01(\x03R\x06shopId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12%\n" +
	"\x0eoriginal_price\x18\x05 \x01(\x03R\roriginalPrice\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"D\n" +
	"\rPriceConflict\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x94\x01\n" +
	"\fCalcPriceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.promotion.CartItemR\x05items\x12\x1d\n" +
	"\n" +
	"coupon_ids\x18\x03 \x03(\x03R\tcouponIds\x12!\n" +
	"\fshipping_fee\x18\x04 \x01(\x03R\vshippingFee\"\xaf\x02\n" +
	"\rCalcPriceResp\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x03R\vtotalAmount\x12-\n" +
	"\x12promotion_discount\x18\x02 \x01(\x03R\x11promotionDiscount\x12'\n" +
	"\x0fcoupon_discount\x18\x03 \x01(\x03R\x0ecouponDiscount\x12!\n" +
	"\fshipping_fee\x18\x04 \x01(\x03R\vshippingFee\x12\x1f\n" +
	"\vpaid_amount\x18\x05 \x01(\x03R\n" +
	"paidAmount\x12'\n" +
	"\x0fdiscount_detail\x18\x06 \x01(\tR\x0ediscountDetail\x126\n" +
	"\tconflicts\x18\a \x03(\v2\x18.promotion.PriceConflictR\tconflicts\"b\n" +
	"\rLockCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"coupon_ids\x18\x03 \x03(\x03R\tcouponIds\"-\n" +
	"\x10ReleaseCouponReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"-\n" +
	"\x10ConsumeCouponReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"?\n" +
	"\n" +
	"RefundItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"x\n" +
	"\rCalcRefundReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vfull_refund\x18\x02 \x01(\bR\n" +
	"fullRefund\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.promotion.RefundItemR\x05items\"Z\n" +
	"\x0eCalcRefundResp\x12#\n" +
	"\rrefund_amount\x18\x01 \x01(\x03R\frefundAmount\x12#\n" +
	"\rrefund_detail\x18\x02 \x01(\tR\frefundDetail2\xf3\b\n" +
	"\tPromotion\x12M\n" +
	"\x0eCreateActivity\x12\x1c.promotion.CreateActivityReq\x1a\x1d.promotion.CreateActivityResp\x12D\n" +
	"\vGetActivity\x12\x19.promotion.GetActivityReq\x1a\x1a.promotion.GetActivityResp\x12A\n" +
	"\x0eUpdateActivity\x12\x1c.promotion.UpdateActivityReq\x1a\x11.promotion.OkResp\x12M\n" +
	"\x14ChangeActivityStatus\x12\".promotion.ChangeActivityStatusReq\x1a\x11.promotion.OkResp\x12M\n" +
	"\x0eListActivities\x12\x1c.promotion.ListActivitiesReq\x1a\x1d.promotion.ListActivitiesResp\x12_\n" +
	"\x14CreateCouponTemplate\x12\".promotion.CreateCouponTemplateReq\x1a#.promotion.CreateCouponTemplateResp\x12\\\n" +
	"\x13ListCouponTemplates\x12!.promotion.ListCouponTemplatesReq\x1a\".promotion.ListCouponTemplatesResp\x12Y\n" +
	"\x1aChangeCouponTemplateStatus\x12(.promotion.ChangeCouponTemplateStatusReq\x1a\x11.promotion.OkResp\x12J\n" +
	"\rReceiveCoupon\x12\x1b.promotion.ReceiveCouponReq\x1a\x1c.promotion.ReceiveCouponResp\x12J\n" +
	"\rListMyCoupons\x12\x1b.promotion.ListMyCouponsReq\x1a\x1c.promotion.ListMyCouponsResp\x12>\n" +
	"\tCalcPrice\x12\x17.promotion.CalcPriceReq\x1a\x18.promotion.CalcPriceResp\x129\n" +
	"\n" +
	"LockCoupon\x12\x18.promotion.LockCouponReq\x1a\x11.promotion.OkResp\x12?\n" +
	"\rReleaseCoupon\x12\x1b.promotion.ReleaseCouponReq\x1a\x11.promotion.OkResp\x12?\n" +
	"\rConsumeCoupon\x12\x1b.promotion.ConsumeCouponReq\x1a\x11.promotion.OkResp\x12A\n" +
	"\n" +
	"CalcRefund\x12\x18.promotion.CalcRefundReq\x1a\x19.promotion.CalcRefundRespB\rZ\v./promotionb\x06proto3"

var (
	file_promotion_promotion_proto_rawDescOnce sync.Once
	file_promotion_promotion_proto_rawDescData []byte
)

func file_promotion_promotion_proto_rawDescGZIP() []byte {
	file_promotion_promotion_proto_rawDescOnce.Do(func() {
		file_promotion_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promotion_promotion_proto_rawDesc), len(file_promotion_promotion_proto_rawDesc)))
	})
	return file_promotion_promotion_proto_rawDescData
}

var file_promotion_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_promotion_promotion_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: promotion.Empty
	(*OkResp)(nil),                        // 1: promotion.OkResp
	(*ActivityTarget)(nil),                // 2: promotion.ActivityTarget
	(*ActivityAction)(nil),                // 3: promotion.ActivityAction
	(*ActivityRule)(nil),                  // 4: promotion.ActivityRule
	(*Activity)(nil),                      // 5: promotion.Activity
	(*CreateActivityReq)(nil),             // 6: promotion.CreateActivityReq
	(*CreateActivityResp)(nil),            // 7: promotion.CreateActivityResp
	(*GetActivityReq)(nil),                // 8: promotion.GetActivityReq
	(*GetActivityResp)(nil),               // 9: promotion.GetActivityResp
	(*UpdateActivityReq)(nil),             // 10: promotion.UpdateActivityReq
	(*ChangeActivityStatusReq)(nil),       // 11: promotion.ChangeActivityStatusReq
	(*ListActivitiesReq)(nil),             // 12: promotion.ListActivitiesReq
	(*ListActivitiesResp)(nil),            // 13: promotion.ListActivitiesResp
	(*CouponTemplate)(nil),                // 14: promotion.CouponTemplate
	(*CreateCouponTemplateReq)(nil),       // 15: promotion.CreateCouponTemplateReq
	(*CreateCouponTemplateResp)(nil),      // 16: promotion.CreateCouponTemplateResp
	(*ListCouponTemplatesReq)(nil),        // 17: promotion.ListCouponTemplatesReq
	(*ListCouponTemplatesResp)(nil),       // 18: promotion.ListCouponTemplatesResp
	(*ChangeCouponTemplateStatusReq)(nil), // 19: promotion.ChangeCouponTemplateStatusReq
	(*Coupon)(nil),                        // 20: promotion.Coupon
	(*ReceiveCouponReq)(nil),              // 21: promotion.ReceiveCouponReq
	(*ReceiveCouponResp)(nil),             // 22: promotion.ReceiveCouponResp
	(*ListMyCouponsReq)(nil),              // 23: promotion.ListMyCouponsReq
	(*ListMyCouponsResp)(nil),             // 24: promotion.ListMyCouponsResp
	(*CartItem)(nil),                      // 25: promotion.CartItem
	(*PriceConflict)(nil),                 // 26: promotion.PriceConflict
	(*CalcPriceReq)(nil),                  // 27: promotion.CalcPriceReq
	(*CalcPriceResp)(nil),                 // 28: promotion.CalcPriceResp
	(*LockCouponReq)(nil),                 // 29: promotion.LockCouponReq
	(*ReleaseCouponReq)(nil),              // 30: promotion.ReleaseCouponReq
	(*ConsumeCouponReq)(nil),              // 31: promotion.ConsumeCouponReq
	(*RefundItem)(nil),                    // 32: promotion.RefundItem
	(*CalcRefundReq)(nil),                 // 33: promotion.CalcRefundReq
	(*CalcRefundResp)(nil),                // 34: promotion.CalcRefundResp
}
var file_promotion_promotion_proto_depIdxs = []int32{
	2,  // 0: promotion.Activity.targets:type_name -> promotion.ActivityTarget
	3,  // 1: promotion.Activity.actions:type_name -> promotion.ActivityAction
	4,  // 2: promotion.Activity.rule:type_name -> promotion.ActivityRule
	2,  // 3: promotion.CreateActivityReq.targets:type_name -> promotion.ActivityTarget
	3,  // 4: promotion.CreateActivityReq.actions:type_name -> promotion.ActivityAction
	4,  // 5: promotion.CreateActivityReq.rule:type_name -> promotion.ActivityRule
	5,  // 6: promotion.GetActivityResp.activity:type_name -> promotion.Activity
	2,  // 7: promotion.UpdateActivityReq.targets:type_name -> promotion.ActivityTarget
	3,  // 8: promotion.UpdateActivityReq.actions:type_name -> promotion.ActivityAction
	4,  // 9: promotion.UpdateActivityReq.rule:type_name -> promotion.ActivityRule
	5,  // 10: promotion.ListActivitiesResp.activities:type_name -> promotion.Activity
	14, // 11: promotion.ListCouponTemplatesResp.templates:type_name -> promotion.CouponTemplate
	20, // 12: promotion.ListMyCouponsResp.coupons:type_name -> promotion.Coupon
	25, // 13: promotion.CalcPriceReq.items:type_name -> promotion.CartItem
	26, // 14: promotion.CalcPriceResp.conflicts:type_name -> promotion.PriceConflict
	32, // 15: promotion.CalcRefundReq.items:type_name -> promotion.RefundItem
	6,  // 16: promotion.Promotion.CreateActivity:input_type -> promotion.CreateActivityReq
	8,  // 17: promotion.Promotion.GetActivity:input_type -> promotion.GetActivityReq
	10, // 18: promotion.Promotion.UpdateActivity:input_type -> promotion.UpdateActivityReq
	11, // 19: promotion.Promotion.ChangeActivityStatus:input_type -> promotion.ChangeActivityStatusReq
	12, // 20: promotion.Promotion.ListActivities:input_type -> promotion.ListActivitiesReq
	15, // 21: promotion.Promotion.CreateCouponTemplate:input_type -> promotion.CreateCouponTemplateReq
	17, // 22: promotion.Promotion.ListCouponTemplates:input_type -> promotion.ListCouponTemplatesReq
	19, // 23: promotion.Promotion.ChangeCouponTemplateStatus:input_type -> promotion.ChangeCouponTemplateStatusReq
	21, // 24: promotion.Promotion.ReceiveCoupon:input_type -> promotion.ReceiveCouponReq
	23, // 25: promotion.Promotion.ListMyCoupons:input_type -> promotion.ListMyCouponsReq
	27, // 26: promotion.Promotion.CalcPrice:input_type -> promotion.CalcPriceReq
	29, // 27: promotion.Promotion.LockCoupon:input_type -> promotion.LockCouponReq
	30, // 28: promotion.Promotion.ReleaseCoupon:input_type -> promotion.ReleaseCouponReq
	31, // 29: promotion.Promotion.ConsumeCoupon:input_type -> promotion.ConsumeCouponReq
	33, // 30: promotion.Promotion.CalcRefund:input_type -> promotion.CalcRefundReq
	7,  // 31: promotion.Promotion.CreateActivity:output_type -> promotion.CreateActivityResp
	9,  // 32: promotion.Promotion.GetActivity:output_type -> promotion.GetActivityResp
	1,  // 33: promotion.Promotion.UpdateActivity:output_type -> promotion.OkResp
	1,  // 34: promotion.Promotion.ChangeActivityStatus:output_type -> promotion.OkResp
	13, // 35: promotion.Promotion.ListActivities:output_type -> promotion.ListActivitiesResp
	16, // 36: promotion.Promotion.CreateCouponTemplate:output_type -> promotion.CreateCouponTemplateResp
	18, // 37: promotion.Promotion.ListCouponTemplates:output_type -> promotion.ListCouponTemplatesResp
	1,  // 38: promotion.Promotion.ChangeCouponTemplateStatus:output_type -> promotion.OkResp
	22, // 39: promotion.Promotion.ReceiveCoupon:output_type -> promotion.ReceiveCouponResp
	24, // 40: promotion.Promotion.ListMyCoupons:output_type -> promotion.ListMyCouponsResp
	28, // 41: promotion.Promotion.CalcPrice:output_type -> promotion.CalcPriceResp
	1,  // 42: promotion.Promotion.LockCoupon:output_type -> promotion.OkResp
	1,  // 43: promotion.Promotion.ReleaseCoupon:output_type -> promotion.OkResp
	1,  // 44: promotion.Promotion.ConsumeCoupon:output_type -> promotion.OkResp
	34, // 45: promotion.Promotion.CalcRefund:output_type -> promotion.CalcRefundResp
	31, // [31:46] is the sub-list for method output_type
	16, // [16:31] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_promotion_promotion_proto_init() }
func file_promotion_promotion_proto_init() {
	if File_promotion_promotion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promotion_promotion_proto_rawDesc), len(file_promotion_promotion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promotion_promotion_proto_goTypes,
		DependencyIndexes: file_promotion_promotion_proto_depIdxs,
		MessageInfos:      file_promotion_promotion_proto_msgTypes,
	}.Build()
	File_promotion_promotion_proto = out.File
	file_promotion_promotion_proto_goTypes = nil
	file_promotion_promotion_proto_depIdxs = nil
}
